### ISSUE TITLE
"Uncaught SyntaxError: Identifier 'useCallback' has already been declared" when imported explicitly

### ISSUE THREAD

**Issue by lsdsjy** [antfu/unplugin-auto-import#10]
My configuration for a vite + react project is as follows:
```
    AutoImport({
      imports: ['react'],
    }),
```

When I installed and configured this plugin, started the vite server and opened the page, there's this error as the title suggests. I suppose this plugin should not conflict with existing imports.

**Comment by antfu** [comment]
Can you share the file that causing the conflict?

**Comment by lsdsjy** [comment]
https://github.com/lsdsjy/auto-import-bug-reprod
Here I made a fresh repo and reproduced the error.
