### ISSUE TITLE
[auto-import] identifier useFetch already defined with @nuxtjs/composition-api

### ISSUE THREAD

**Issue by sondh0127** [antfu/unplugin-auto-import#107]
How can I tell auto-import exclude `useFetch` from `@nuxtjs/composition-api`

My config (Nuxt-2)

```js
[
  'unplugin-auto-import/nuxt',
  {
    imports: ['@nuxtjs/composition-api', '@vueuse/core'],
  },
],
```

Error:
![image](https://user-images.githubusercontent.com/62163604/148738938-585c1e85-7231-423f-800c-c1724d595dc6.png)

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-auto-import/blob/11bc3cbd63e8d60c973a1528e8ff3ee8fa276600/src/types.ts#L68-L73
