### ISSUE TITLE
Typescript type definition files are no longer generated automatically

### ISSUE THREAD

**Issue by jiagang** [antfu/unplugin-auto-import#111]
Webpack+Typescript，"auto-imports.d.ts file" will not be generated if there is no custom resolvers in the configuration. Please confirm whether this is correct?
https://github.com/antfu/unplugin-auto-import/commit/8d1cdcd6c0d17f830e3238085c7bcbbe894e45c2
![image](https://user-images.githubusercontent.com/3692361/149865175-49682a64-d532-4305-b795-e0b7a607492d.png)

**Comment by antfu** [comment]
It's a bug that we moving the generation timing for Vite but forgot to consider Webpack. PR welcome to fix it
