### ISSUE TITLE
generator is not working properly

### ISSUE THREAD

**Issue by Rasool-deldar** [antfu/unplugin-auto-import#113]
Hello, good morning
I used your plugin in nuxt 2 but unfortunately the file does not output and does not work properly 
Inside the terminal and the editor also gives an error saying your syntax is incorrect, please help this problem

[exmple](https://codesandbox.io/s/angry-cherry-evtzc?file=/pages/index.vue)

**Comment by DevilTea** [comment]
I have the same problem.
Here's my workaround
```js
// your AutoImport options
{
  ...
  resolvers: [() => null]
  ...
}
```

**Comment by Rasool-deldar** [comment]
> ```js
>   resolvers: [() => null]
> ```

thanks for your help
