### ISSUE TITLE
Webpack+Typescript .eslintrc-auto-import.json does not automatically generate

### ISSUE THREAD

**Issue by 178308360** [antfu/unplugin-auto-import#114]
Webpack+Typescript，".eslintrc-auto-import.json" will not be generated

**Comment by joker77877** [comment]
I had the same problem, how did you solve it?

**Comment by 178308360** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antfu/unplugin-auto-import"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 中午11:56
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [antfu/unplugin-auto-import] Webpack+Typescript .eslintrc-auto-import.json does not automatically generate (Issue #114)





 
I had the same problem, how did you solve it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PeterChen1997** [comment]
same problem

**Comment by baok1592** [comment]
vue.config.js 中的配置 enabled: true  要先开启，生成后在关闭，避免重复生成
