### ISSUE TITLE
Values in vue templates don't trigger auto-import

### ISSUE THREAD

**Issue by josh-hemphill** [antfu/unplugin-auto-import#115]
If looking at the template itself isn't a good idea, perhaps some dev-facing comment directives or config options to set more limited matching for specific use cases could be helpful.

To give an example. I can do the following, but I have to add the variable names to something in the script block for it to work, which kind of defeats the purpose.
```ts
AutoImport({
	imports: [
		'vue',
                {
                	'@mdi/js': Object.keys(await import('@mdi/js')).filter(v=>v.startsWith('mdi')),
                }
	],
}),
```

```vue
<script setup lang="ts">
// Ideally I wouldn't end up with having to write out import statements with 12+ different variables
// but to get them to auto-import, I've got to do something like this:
const i = {mdiInformationOutline}

// And I can't just do `import * as i from '@mdi/js'` because then it doesn't get tree shook, and I end up with 2MB+ file
</script>
<template>
  <main class="px-4 py-10 text-center text-teal-700 dark:text-gray-200">
    <div>
      <p class="text-4xl">
        <v-icon :icon="i.mdiInformationOutline" class="inline-block" />
      </p>
    </div>
    <router-view />
  </main>
</template>
```

**Comment by antfu** [comment]
A bit unrelated, but how about giving a try to https://github.com/antfu/unocss/tree/main/packages/preset-icons ? 👀

**Comment by josh-hemphill** [comment]
> A bit unrelated, but how about giving a try to https://github.com/antfu/unocss/tree/main/packages/preset-icons ? 👀
Sorry, I should have clarified, I'm importing SVG paths (not SVGs themselves) and passing it onto Vuetify icon components so that the icons inherit their properties from the Vuetify instance. I don't think unocss preset-icons would work for that.

**Comment by josh-hemphill** [comment]
If you have any suggestions for being able to treeshake unused properties of a global value, that would also be a means to accomplish what I'm trying to do. I'm using vite-ssg, so most of these icon paths get inlined anyways, so having the whole of `@mdi/js` added to the bundle is really frustrating.

**Comment by josh-hemphill** [comment]
Would adding the ability to detect variables within templates be in scope for this project?
Looking at the code everything looks pretty straight forward; perhaps the way to go would be to add another set of resolver/preset options (disabled by default for compatibility) that can provide the regexes for framework specific template variable detection? I'd be happy to open a PR.

**Comment by antfu** [comment]
Shipped in v0.8.0

**Comment by websitevirtuoso** [comment]
I am trying to achieve the same goal.
What kind of autoImport config do you have?
@josh-hemphill

**Comment by josh-hemphill** [comment]
It's listed in the Readme.md, just set `vueTemplate` to `true`.
[link to line where it's specified](https://github.com/antfu/unplugin-auto-import/blob/main/README.md?plain=1#L215)

**Comment by websitevirtuoso** [comment]
I already have this parameter but still can't use mdi icons 
![image](https://user-images.githubusercontent.com/5112918/191853722-2a3f20d9-5eb8-4153-b665-776143456643.png)

I expect to have something like this but with autoImport

![image](https://user-images.githubusercontent.com/5112918/191853821-3cd49520-7cc0-42aa-86f4-c8b36439b8b9.png)

**Comment by josh-hemphill** [comment]
You're missing the `await` before the `import()`

**Comment by websitevirtuoso** [comment]
Thanks.
