### ISSUE TITLE
Conflict with `unplugin-vue-components`

### ISSUE THREAD

**Issue by sxzz** [antfu/unplugin-auto-import#116]
`unplugin-auto-import` must transform code before `unplugin-vue-components` does.

## Rollup / Vite

Reproduction: https://github.com/sxzz/element-plus-best-practices

https://github.com/sxzz/element-plus-best-practices/blob/6618dd3295c9f97ede152ba671ce0982afb4d242/vite.config.ts#L33-L43

If you put `Components` before `AutoImport`, it will emits errors.

```
[plugin:vite:import-analysis] Failed to resolve import "element-plus/es/components/loading-directive/style/css" from "src/App.vue". Does the file exist?
/some/path/src/App.vue:1:109
1  |  import { ElLoadingDirective, ElSpace, ElInput, ElButton, ElIcon, ElMessage } from 'element-plus/es';import 'element-plus/es/components/loading-directive/style/css';import 'element-plus/es/components/space/style/css';import 'element-plus/es/components/input/style/css';import 'element-plus/es/components/button/style/css';import 'element-plus/es/components/icon/style/css';import { defineComponent, ref, resolveComponent } from 'vue';import 'element-plus/es/components/message/style/css';/* unplugin-vue-components disabled */import { ElLoadingDirective as __unplugin_directives_0 } from 'element-plus/es';import 'element-plus/es/components/loading/style/css';
   |                                                                                                              ^
2  |  import { ElSpace as __unplugin_components_6 } from 'element-plus/es';import 'element-plus/es/components/space/style/css';
3  |  import { ElInput as __unplugin_components_5 } from 'element-plus/es';import 'element-plus/es/components/input/style/css';
```

### Reason

`ElLoadingDirective` is imported by `unplugin-vue-components`, and `unplugin-auto-import` also handled it. For more detail, you can use vite-plugin-inspect to debug it.

## Webpack

Reproduction: https://github.com/cxj-github/auto-import-demo

`unplugin-auto-import` add option `enforce`: `post`, so `unplugin-vue-components` must be executed before `unplugin-auto-import`. There seems to be no workaround to avoid it.

Related issue: https://github.com/element-plus/element-plus/issues/4855

**Comment by sxzz** [comment]
Related issue: #127

**Comment by Manu-Geotourist** [comment]
@antfu
