### ISSUE TITLE
auto import type of component

### ISSUE THREAD

**Issue by BhaskaranR** [antfu/unplugin-auto-import#118]
Greatly appreciate the work that you have done. 

Types for the Components registered for auto import is not available globally.  In this case ErrorModal is registered for auto-import I need the type of the element that i am trying to reference here. Cannot find name 'ErrorModal'

```
const errorModal = ref<InstanceType<typeof ErrorModal> | null>(null);
```

is there any fix for this?

**Comment by dammy001** [comment]
Can you reproduce this and provide a link?

**Comment by antfu** [comment]
#61
