### ISSUE TITLE
Usage without TypeScript

### ISSUE THREAD

**Issue by ttxtosca** [antfu/unplugin-auto-import#12]
Hello!

I gave a try with vitesse template and a standalone vite project, everything seams to work quite well.. except when I'm not using typescript (eg. no "lang='ts'" and/or no tsconfig.json).

Maybe this library is designed to work especially with TS? But the samples in the readme do not include any TS (except vite config example) ; while playground and nuxt example do.

I'm using vite, vue 3 and <script setup> format.

**Comment by antfu** [comment]
I don't see a problem of using without TS as TS is only provided as some hint and the functionality is provided in js indeed.

If you have any issue on that, please provide a minimal reproduction. Thanks.

**Comment by ttxtosca** [comment]
Hey @antfu,

Made a minimal repro : https://github.com/ttxtosca/unplugin-auto-import-issue-12

From vite/vue start template. `auto-imports.d.ts` is fully populated but from [components/HelloWorld.vue](https://github.com/ttxtosca/unplugin-auto-import-issue-12/blob/master/src/components/HelloWorld.vue), got the error `ReferenceError: ref is not defined` while import line is commented (or not present).

Thank you for your time. I think this is an issue ; except if I missed something.

**Comment by ttxtosca** [comment]
Works like a charm. Thank you for this and your work!
