### ISSUE TITLE
It is not always automatic completion.

### ISSUE THREAD

**Issue by psrx** [antfu/unplugin-auto-import#121]
```html
<script setup>
  import { ref } from 'vue'
  const value = ref(1)
</script>

<template>
  {{ value }}
</template>
```

```html
<script setup>
  const value = ref(1)
</script>

<template>
  {{ value }}
</template>
```

But both can be used normally
I should choose the former, right?  

The latter does not look like typescript support

**Comment by psrx** [comment]
Generate corresponding .eslintrc-auto-import.json file

I tried my best and didn't generate this file 
I deleted the config... 😄

**Comment by antfu** [comment]
You need to enable dts for typescript support. Refer to https://github.com/antfu/vitesse
