### ISSUE TITLE
Add support for `solidjs` 

### ISSUE THREAD

**Issue by gawlk** [antfu/unplugin-auto-import#122]
Hi !

Very useful library, it really does save time and space in the codebase. It would be really awesome if you could support other frameworks especially `solidjs` which is getting more popular everyday.

Anyway, thanks for your work !

**Comment by Netherlander** [comment]
Added support for `solid js` similarly to `react`. @antfu , can I please make a pull request?

**Comment by userquin** [comment]
@Netherlander sure
