### ISSUE TITLE
how to auto import "SetupContext"?

### ISSUE THREAD

**Issue by liugui** [antfu/unplugin-auto-import#129]
As we known, "ref"、"reactive" will be auto imported from vue with unplugin-auto-import. However, I can't see "SetupContext" in auto-imports.d.ts. If I add it manually, the typescript errors is show.  How to resolve this problem?
![image](https://user-images.githubusercontent.com/9071746/154442197-4dec786f-5257-4a6c-a04f-f69f442844db.png)

**Comment by sxzz** [comment]
TS typings will not imported. Related issue: #61

**Comment by antfu** [comment]
Duplicate of https://github.com/antfu/unplugin-auto-import/issues/61
