### ISSUE TITLE
Support automatic import vue components

### ISSUE THREAD

**Issue by liamwang** [antfu/unplugin-auto-import#130]
Expecting a new feature to support automatic import vue components. 

The expected `vite.config.ts` configuration might look like this:

```ts
// ...

export default defineConfig({
  resolve: {
    alias: {
      '@/': `${path.resolve(__dirname, 'src')}/`,
    },
  },
  plugins: [
    // ...
    AutoImport({
      imports: [
        'vue',
        'vue-router',
        {
          module: 'vue',
          components: { 
            'lib-name': ['ComponentA', ['ComponentB', 'ComponentBAlias']] 
          },
        },
      ],
    }),
    // ...
})
```

The automatically generated `.d.ts` file will look like the following:

```ts
declare global {
  // ...
}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentA: typeof import('lib-name')['ComponentA']
    ComponentBAlias: typeof import('lib-name')['ComponentB']
  }
}
```

Thank you guys!

**Comment by zynth17** [comment]
you can use [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) to have component auto importing

**Comment by liamwang** [comment]
@zynth17  I considered using [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components), but for third-party libraries, it only generates declarations in the `.d.ts` file when running to the component. This does not get the benefit of TypeScript intellisense in most cases.

**Comment by antfu** [comment]
[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) is the way to go
