### ISSUE TITLE
Unable to resolve path to module 'unplugin-auto-import/vite'

### ISSUE THREAD

**Issue by DrJume** [antfu/unplugin-auto-import#136]
After updating to `unplugin-auto-import@0.6.4` eslint cannot resolve to this module.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by sxzz** [comment]
Please just disable `import/no-unresolved` rule, since you're already using TypeScript. The TypeScript compiler will check this.

**Comment by wJoenn** [comment]
What if I'm not using TS ?
