### ISSUE TITLE
how to auto import ‘lodash-es’

### ISSUE THREAD

**Issue by JackieCheung** [antfu/unplugin-auto-import#147]

**Comment by JackieCheung** [comment]
current usage:

`imports: [
          'vue',
          'pinia',
          'vue-router',
          '@vueuse/core',
          {
            'lodash-es': ['cloneDeep', 'camelCase', 'isPlainObject', 'merge']
          }
        ]`

Is there a better way?🤔

**Comment by dammy001** [comment]
@JackieCheung I think this is much better since `lodash-es` is not part of the default plugins. Are you facing any issues with your current usage?
