### ISSUE TITLE
是否支持通过cdn形式引入vue3的场景

### ISSUE THREAD

**Issue by ZhangYang-hand** [antfu/unplugin-auto-import#149]
经测试发现本地开发环境自动引入的vue指向本地包，打包发布到线上我采用了引入cdn的vue，会存在找不到vue的情况，原因应该是指向的vue代码还是下载的vue。这种情况怎么解决呢？是配置问题吗？

**Comment by Autumnwater** [comment]
事实上不行，因为会把 import {ref} from vue打入到dist内

**Comment by Autumnwater** [comment]
写一个banle插件啊吧，每次打包后把from vue改成from //：acnd
