### ISSUE TITLE
SvelteKit: Auto import src/components

### ISSUE THREAD

**Issue by MentalGear** [antfu/unplugin-auto-import#154]
I'm struggling for how to define custom paths/folders to auto import files from. For example, using sveltekit, I would like to have all files in /components detected for importing. (I tried to use "Custom Resolvers" but it lacks a clear example - only links to a pull request.)

**Comment by paulalbertdev** [comment]
Don't you want this https://github.com/antfu/unplugin-vue-components ?

**Comment by antfu** [comment]
Auto importing for components is out-of-scope of this plugin.

**Comment by MentalGear** [comment]
So this only auto imports functions, not component files? Would be better then to clearly state the scope in the readme.
