### ISSUE TITLE
how to auto import module like this:  import defaultExport from "module-name"

### ISSUE THREAD

**Issue by cjq02** [antfu/unplugin-auto-import#162]
I tried all kinds of different ways of writing, but still can't achieve such a reference:

import dayjs from 'dayjs'
import _ from 'lodash'

**Comment by cjq02** [comment]
If I wirte like this:

```
AutoImport({
  import: [
    {
      'dayjs': [['*', 'dayjs']]
    }
  ]
})
```


It will execute an error in the production environment

**Comment by Jungzl** [comment]
use this config instead
```javascript
AutoImports({
    imports: [
      {
        'dayjs': [['default', 'dayjs']]
      }
    ]
  })
```

**Comment by cjq02** [comment]
> use this config instead
> 
> ```js
> AutoImports({
>     imports: [
>       {
>         'dayjs': [['default', 'dayjs']]
>       }
>     ]
>   })
> ```

Such a configuration can indeed solve this problem, but in the generated auto-imports.d.ts file, the related type will throw a TS2339 exception, because the type does not export default：
![image](https://user-images.githubusercontent.com/16457309/163705579-baed4ca4-2368-43c4-b3da-185bca83aee4.png)
In this case, I think `import dayjs from 'dayjs'` would be better than `import { default as dayjs } from 'dayjs'`

**Comment by Inori-Lover** [comment]
as now, i found a workround
```
// @/utils/dayjs.ts
import * as dayjs from 'dayjs'
export { dayjs }
```


````
// autoImportConfig
{
    // ...,
    imports: [{ "@/utils/dayjs": [["dayjs", "dayjs"]] }]
}
```

**Comment by Inori-Lover** [comment]
as now, i found a workround
```
// @/utils/dayjs.ts
import * as dayjs from 'dayjs'
export { dayjs }
```


````
// autoImportConfig
{
    // ...,
    imports: [{ "@/utils/dayjs": [["dayjs", "dayjs"]] }]
}
```

**Comment by cjq02** [comment]
> a workround
> 
> ```
> // '@/utils/dayjs.ts'
> import * as dayjs from 'dayjs'
> export { dayjs }
> ```
> 
> ```
> // autoImportConfig
> {
>     // ...,
>     imports: [{ "@/utils/dayjs": [["dayjs", "dayjs"]] }]
> }
> ```
> ```

looks fine

**Comment by antfu** [comment]
Close as I think it's more like a type issue on dayjs.
