### ISSUE TITLE
Haven't included all ElementPlus components used in script

### ISSUE THREAD

**Issue by YornQiu** [antfu/unplugin-auto-import#165]
If you reopen a project developed before, the auto-imports.d.ts generated by this plugin only included the components in the pages you opened.

1) Using ElMessage,ElNofitication in two different pages.
2) The auto-imports.d.ts will include ElMessage and ElNofitication.
3) Reopen the project.
4) Open the page that used ElMessage this time, don't open the other page.
5) The auto-imports.d.ts will only include ElMessage, ElNofiticationis ignored.

This may cause error when building.
You can get more info in this issue:https://github.com/element-plus/element-plus/issues/6947.

Looking forward to reply.

**Comment by pany-ang** [comment]
Same problem

**Comment by DaniilCome1n** [comment]
Same problem

**Comment by zhanxiaoge** [comment]
Same problem

**Comment by drsmile1001** [comment]
same problem

**Comment by AprilTong** [comment]
The problem still exists, why close the issue？

**Comment by Spike-Leung** [comment]
same problem

**Comment by huagelong** [comment]
same problem

**Comment by fayeah** [comment]
same problem, related components:

el-message-box
el-message
el-notification

**Comment by earthaYan** [comment]
the problem  still exist in the latest version@antfu
