### ISSUE TITLE
wepack + ts + react cannot auto generate d.ts and auto-import.js

### ISSUE THREAD

**Issue by PeterChen1997** [antfu/unplugin-auto-import#166]
wepack + ts + react cannot auto generate d.ts and auto-import.js

with `webpack-dev-server` or `webpack`

**Comment by PeterChen1997** [comment]
"webpack": "^5.58.2",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.7.4"

**Comment by harrytran998** [comment]
Yeah, I had the same problem with Nextjs using webpack example.

**Comment by lishaobos** [comment]
need reproduction...
