### ISSUE TITLE
use volar + autoimport can`t use volar:Auto Complete Refs

### ISSUE THREAD

**Issue by Chenjiaxing233** [antfu/unplugin-auto-import#167]
use volar + vuecli + unplugin-auto-import, can not  use  volar to auto complete Ref value with `.value`;
if you `import  {ref} from 'vue'` volar can auto complete `.value`

**Comment by antfu** [comment]
This is probably one caveat. I don't see there is anything we could do on our side to support it.

**Comment by AAABingBing** [comment]
How do you avoid auto-import every time `Vue - Official` extends the feature using `unplugin-auto-import`?

For example, if I type ref, it will automatically `import { ref } from 'vue'`
But I've already used `unplugin-auto-import`, how do I turn off `Vue - Official` auto-import?

**Comment by AAABingBing** [comment]
> This is probably one caveat. I don't see there is anything we could do on our side to support it.

How do you avoid auto-import every time `Vue - Official` extends the feature using `unplugin-auto-import`?

For example, if I type ref, it will automatically `import { ref } from 'vue'`
But I've already used `unplugin-auto-import`, how do I turn off `Vue - Official` auto-import?
