### ISSUE TITLE
Recommended way to use both vue and nuxt composition api presets

### ISSUE THREAD

**Issue by gustojs** [antfu/unplugin-auto-import#17]
`@nuxtjs/composition-api` preset is good but when I try to load also `@vue/composition-api` preset to get TS interfaces, I end up with ` ERROR  [auto-import] identifier onActivated already defined with @vue/composition-api`.

What's the recommended solution for using two presets that partly overwrite each other? Should I add missing stuff individually as an array?

**Comment by userquin** [comment]
@gustojs `@nuxt/composition-api` also includes `@vue/composition-api`, you don't need to add it, just see `nuxt.ts` on `src/presets` directory.

**Comment by gustojs** [comment]
Ah, that makes sense. When I noticed that the TypeScript interfaces are not included in Nuxt preset, I assumed they were in Vue preset. But it turns out they weren't there anyways.

That solves the dilemma, thx!

I'll close it.

**Comment by gustojs** [comment]
Let me just refer it for anybody searching for it. There's actually an option `presetOverriding` that allows to override types between presets, by default set to false.

https://github.com/antfu/unplugin-auto-import/blob/main/src/types.ts#L41
