### ISSUE TITLE
unplugin-auto-import 生成的auto-imports.d.ts 打包后类型就丢失一些了

### ISSUE THREAD

**Issue by huzedong2015** [antfu/unplugin-auto-import#170]
unplugin-auto-import 生成的auto-imports.d.ts 打包后类型就丢失一些了

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
