### ISSUE TITLE
eslintrc-auto-import.json Not found（maybe not auto generated）

### ISSUE THREAD

**Issue by xiangqunXiao** [antfu/unplugin-auto-import#173]
# How to repeoduce
- clone https://github.com/xiangqunXiao/elem-ts/tree/test
- follow steps: https://github.com/xiangqunXiao/elem-ts/blob/test/README.md#bug-repoduce

# Enviroment
OS: Win10 WSL2 Ubuntu
Editor: VSCode
Node: v16.13.2
Pnpm: 6.11.0

**Comment by abitwhy** [comment]
# Solution

```ts
AutoImport({
  // ...
  eslintrc: {
    enabled: true,
  }
})
```
As you see, it's not a bug, please check [the configuration](https://github.com/antfu/unplugin-auto-import#configuration) first.

**Comment by abitwhy** [comment]
And there is a real bug if set a custom `eslintrc.filepath` like `./temp/.eslintrc-global.json`. Then when you install your project for the first time, it will fail with the error report: 

```log
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: ENOENT: no such file or directory, open 'E:\vue3-fast\temp\.eslintrc-global.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'E:\\vue3-fast\\temp\\.eslintrc-global.json'
}
 ELIFECYCLE  Command failed with exit code 1.
```
You have to create the folder `/temp` by hand to make it work.
Is this due to lacking the permission of creating a folder?

**Comment by xiangqunXiao** [comment]
@abitwhy  it will be auto generated only in the situaction when I run npm `dev` scripts?

**Comment by lishaobos** [comment]
> @abitwhy it will be auto generated only in the situaction when I run npm `dev` scripts?

Step1:

```js
// vite.config

AutoImport({
  // ...
  eslintrc: {
    enabled: true,
  }
}),
Components({
   dts: './src/components.d.ts',
})
```

Step2:

```js
// .eslintrc

{
  "extends": [
    // ...
    "../.eslintrc-auto-import.json"
  ]
}
```

Step3:

bacause pnpm has bug with volar, so you need add @vue/runtime-core in your devDependencies

```js
pnpm i  @vue/runtime-core -D
```

finally:

![image](https://user-images.githubusercontent.com/46661044/211962850-a549a992-666c-4d72-8a8e-eb7651c2ce83.png)

![image](https://user-images.githubusercontent.com/46661044/211962903-9ac1cb1f-da49-4e77-aefc-93b9fbd3ccb2.png)
