### ISSUE TITLE
关于在vite项目中使用unplugin-auto-import，直接构建不会生成auto-imports.d.ts文件的问题

### ISSUE THREAD

**Issue by wangrongding** [antfu/unplugin-auto-import#179]
具体是这样的：
由于每次生成的`auto-imports.d.ts`都不一样，所以直接把它加入到`.gitignore`文件中。不想每次都带着它提交。（有其他好的方法也可以告知~感激💗）
但如果不执行npm run dev，就无法生成`auto-imports.d.ts`文件。如果直接构建的话就会报错。
比如：
项目在Vercel中自动构建，如果项目中没有这个文件的话，那么就会导致构建失败了。  

请问目前有什么好的解决方案嘛？感谢💗

**Comment by antfu** [comment]
建议 Commit，或者尝试显式开启 dts: true

**Comment by wangrongding** [comment]
好的偶像👍

**Comment by sky124380729** [comment]
> 好的偶像👍

我遇到了同样的问题，文件不停变化，导致每次都要提交这个文件，我把它加入了gitignore，这样又直接导致生产环境由于没有d.ts，使vue-tsc报错了。
你解决了这个问题吗？

**Comment by chaselen** [comment]
我也是😂

**Comment by zettle** [comment]
我也是，想问下怎么解决，执行vue-tsc的时候，不会自动生成d.ts
