### ISSUE TITLE
Can't pass type-checking with vue-tsc

### ISSUE THREAD

**Issue by suzhihao** [antfu/unplugin-auto-import#18]
using https://github.com/antfu/vitesse as example.

src/pages/[...all].vue:2:15 - error TS2304: Cannot find name 'useI18n'.

2 const { t } = useI18n()
                ~~~~~~~

src/layouts/404.vue:2:16 - error TS2304: Cannot find name 'useRouter'.

2 const router = useRouter()
                 ~~~~~~~~~

src/layouts/404.vue:3:15 - error TS2304: Cannot find name 'useI18n'.

3 const { t } = useI18n()
                ~~~~~~~

src/pages/index.vue:5:14 - error TS2304: Cannot find name 'ref'.

5 const name = ref(user.savedName)


![image](https://user-images.githubusercontent.com/4735309/131475611-ed9e51ce-6ab4-4baf-9fea-dc4ac037c2a5.png)

**Comment by suzhihao** [comment]
same as https://github.com/antfu/unplugin-auto-import/issues/13

**Comment by userquin** [comment]
@suzhihao maybe the best fix is to add `dts: './src/auto-imports.d.ts` on plugin configuration and remove it from `tsconfig.json` file.
