### ISSUE TITLE
[Bug Report] - When referencing the keyword inside a string template caused undefined.

### ISSUE THREAD

**Issue by JeremyWuuuuu** [antfu/unplugin-auto-import#185]
## Metadata

```md
OS: macOS Monterey 12.4 Beta (21F5048e)
Model: Macbook Pro (16-inch 2021)
Chip: Apple M1 Max
Mem: 32G
Node Version: 16.12.0 ARM
PackageManager: pnpm 7.0.0
AutoImport Version: 0.8.2
```

The code can be found in [Element Plus Issue Helper](https://github.com/element-plus/element-plus-issue-helper)

## Detailed report:

https://github.com/element-plus/element-plus-issue-helper/blob/c18ea9e025b363482391a862dd74660a25a795bd/src/hooks/forms.ts#L172

The code here is wrapped inside a string template. Running the build command 

```shell
pnpm build
```

The code gets built successfully, but the output contains no definition of the auto imported function `resolveReproductionLink` and `removeReproductionPrefix`.

## Temporary fix

Move the invocation of the auto import function above the string template with

```ts
const linkName = resolveReproductionLink(form.bugReport.reproductionLink)?.name ?? 'Link'
const link = removeReproductionPrefix(form.bugReport.reproductionLink)

const preview = `
[${linkName}](${link})
`
``` 

Now the built product will contain the code definition.

**Comment by JeremyWuuuuu** [comment]
My fix on this bug locally can be found [here](https://github.com/element-plus/element-plus-issue-helper/pull/2)

**Comment by sxzz** [comment]
PR: https://github.com/unjs/unimport/pull/55
