### ISSUE TITLE
vue3 "markRow is not defined"

### ISSUE THREAD

**Issue by TaoziDeGitHub** [antfu/unplugin-auto-import#190]
vue version: 3.2.36
vite version: 2.9.9
unplugin-auto-import version: 0.8.6

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
