### ISSUE TITLE
0.8.8版本编译报错

### ISSUE THREAD

**Issue by lljsw66** [antfu/unplugin-auto-import#207]
安装0.8.8版本后项目编译报错 unexpect token ,  指向双问号运算符报错，
降到0.7.2版本就能正常跑起来

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
