### ISSUE TITLE
The <component is= "" > of vue3 cannot render automatically imported components and icons

### ISSUE THREAD

**Issue by zz541843** [antfu/unplugin-auto-import#208]
`<abc-ep-close/>  // right`
`<component is="abc-ep-close"></component>// not`

**Comment by zz541843** [comment]
![image](https://user-images.githubusercontent.com/72638366/173973261-b8633fd2-cae0-4da1-9ca7-bb44addc5078.png)
Just render it as a html label

**Comment by AlextheXX** [comment]
[issue in unplugin-vue-components](https://github.com/antfu/unplugin-vue-components/issues/11)

**Comment by zz541843** [comment]
> [issue in unplugin-vue-components](https://github.com/antfu/unplugin-vue-components/issues/11)

I don't understand, Is unable to realize dynamic components?

**Comment by antfu** [comment]
For dynamic components, you need to explicitly import them.
