### ISSUE TITLE
Suggest: I think we can count on community to add d.ts preset is a better idea.

### ISSUE THREAD

**Issue by SnowingFox** [antfu/unplugin-auto-import#210]
When use this plugin in typescript, the most import thing is to define d.ts from some lib. But for developers, finding the corresponding type definitions in the d.ts file is undoubtedly a mental burden.
You may say we can do like this
```ts
export {}
delcalare global {
    const watch: typeof import('vue')['watch']
}
```

However, for some ides such as webstorm, it will highlight watch as a variable rather than a function, which is very uncomfortable visually. Therefore, the best way is to copy the corresponding type definitions in the corresponding repo

This is an example for react
```ts
/**
   * Returns a stateful value, and a function to update it.
   *
   * @version 16.8.0
   * @see https://reactjs.org/docs/hooks-reference.html#usestate
   */
  function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>]
  // convenience overload when first argument is omitted
  /**
   * Returns a stateful value, and a function to update it.
   *
   * @version 16.8.0
   * @see https://reactjs.org/docs/hooks-reference.html#usestate
   */
  function useState<S = undefined>(): [S | undefined, Dispatch<SetStateAction<S | undefined>>]
```
thus we can get more powerful intellisense.

Would you consider doing so

**Comment by JounQin** [comment]
> However, for some ides such as webstorm, it will highlight watch as a variable rather than a function, which is very uncomfortable visually. Therefore, the best way is to copy the corresponding type definitions in the corresponding repo

You should raise an issue on webstorm's side IMO.

**Comment by antfu** [comment]
Close as I consider this to be out-of-scope.
