### ISSUE TITLE
结合@formily/element-plus使用时，element-plus样式无法生效

### ISSUE THREAD

**Issue by umi-soft** [antfu/unplugin-auto-import#212]
[点击可提取复现代码地址](https://github.com/umi-soft/question-for-element-plus-resolver/tree/master)

现象描述详见：
![image](https://user-images.githubusercontent.com/13619406/176351265-9df895a2-cd28-41ed-b764-46d1a15981a0.png)

实际验证，如果在`@formily/element-plus`的外层使用`element-plus`组件，样式不受影响，但是在内层使用，就会造成该现象

**Comment by azaleta** [comment]
@umi-soft 
如果在@formily/element-plus的外层使用element-plus组件，样式不受影响 ✔️
但是在内层使用，就会造成该现象 ❌

在内层（Test.vue）你并没有使用element-plus组件，而全部是formily组件
如果你在内层加上element-plus组件（比如el-radio-group），你可以得到正确的显示
所以我觉得这是formily按需导入的问题

时间有限，稍微扫了一眼[resolver](https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/element-plus.ts)

```ts
function resolveComponent(name: string, options: ElementPlusResolverOptionsResolved): ComponentInfo | undefined {
  if (options.exclude && name.match(options.exclude))
    return

  if (!name.match(/^El[A-Z]/))
    return
```

似乎组件名不是EL开头的话 直接跳过，所以formily组件（SchemaField，FormProvider.....)似乎并不能用
Element Plus的resolver

**Comment by umi-soft** [comment]
非常感谢您的回复！
我大致看了下@formily/element-plus的源码，他是在element-plus的基础上做了一层封装，他的代码里面实际上是import XX from element-plus
有没有建议的解决方案呢，主要是我不想用babel-plugin-import

**Comment by azaleta** [comment]
@umi-soft 
[idea](https://github.com/azaleta/formily-autoimport)

我不熟悉 formily
简单看了下 他的组件命名并没有统一的规则（类似以 EL开头）
算一个思路吧 你需要的话可以自己扩展resolver

最终还是需要靠formily团队自己来实现resolver的（因为涉及到sideeffects这些，我是没那点精力全部看的）

**Comment by umi-soft** [comment]
好的，感谢感谢，我关掉这个issues

**Comment by azaleta** [comment]
@umi-soft 
不小心搞成private了 现在好了
