### ISSUE TITLE
Add `createI18n` on `vue-i18n` preset.

### ISSUE THREAD

**Issue by alzawad26** [antfu/unplugin-auto-import#219]
`createI18n` is currently missing from `vue-i18n` preset. Is it possible to add it or is there any reason behind it missing?

**Comment by userquin** [comment]
@alzawad26 we only add stuff that is used multiple times (repetitive), since the `createI18n` is being only used 1 time, you should import it.

**Comment by omnjpa27516** [comment]
Please add `petite-vue-i18n` to i18n preset.

https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/vue-i18n.ts

```
  'petite-vue-i18n': [
    'useI18n',
  ],
```

@userquin @antfu
