### ISSUE TITLE
Cannot assign type "ComponentResolver" to type "Arrayable<Resolver>",why?

### ISSUE THREAD

**Issue by xlgp** [antfu/unplugin-auto-import#227]
![image](https://user-images.githubusercontent.com/26807499/177911322-64edff0f-034c-42e9-8b6b-fe1ce28b1785.png)

 "unplugin-vue-components": "^0.16.0",
 "unplugin-auto-import": "^0.9.2",

**Comment by xlgp** [comment]
can not auto import vue-router。
There is not import vue-router in auto-import.ts, only import vue and @vueuse/core
![image](https://user-images.githubusercontent.com/26807499/177922543-af995780-ce6d-4018-b080-e73635e71e3f.png)
![image](https://user-images.githubusercontent.com/26807499/177922316-4f889cb3-597e-4147-9c1e-7520e5bde568.png)

**Comment by antfu** [comment]
Upgrade your deps

**Comment by xlgp** [comment]
> Upgrade your deps

thanks
