### ISSUE TITLE
Can not auto import nested exports

### ISSUE THREAD

**Issue by yjl9903** [antfu/unplugin-auto-import#236]
### Describe the bug

Folder structure likes this:

![image](https://user-images.githubusercontent.com/30072175/180297094-b48ba2ee-6cd9-4331-9b0a-0ce300733374.png)

The plugin can not analyze the exports of `./src/comps/nest/index.ts`.

In the previous versions, it works fine. But after updating to `v0.9.4`, it broke something.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ihjeci?file=auto-imports.d.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I have published 0.9.5 to revert the behavior change. And make 0.9.4 as 0.10.0 to be explicit.

https://github.com/antfu/unplugin-auto-import/releases/tag/v0.10.0
