### ISSUE TITLE
`dirs` settings cannot import automatically

### ISSUE THREAD

**Issue by hooray** [antfu/unplugin-auto-import#238]
### Describe the bug

In v0.9.2 it works fine, but when I upgrade to v0.10.0, it doesn't work. You can use [vitesse](https://github.com/antfu/vitesse) to test, just upgrade `unplugin-auto-import` to v0.10.0 and run it, you will see:

![image](https://user-images.githubusercontent.com/1574903/180599470-070236d4-43b8-4edd-a45d-e73833482d28.png)

### Reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Seems to work fine for me https://github.com/antfu/vitesse/commit/0d5a777f14094bec73e58a3965e8352cffe1b8f6

Please provide a minimal reproduction

**Comment by Liwoj** [comment]
@antfu Used current version of vitesse (degit + install + run dev) and got same error. 
`auto-imports.d.ts` got overwritten and is missing `const isDark: typeof import('./composables/dark')['isDark']`

Maybe problem is I'm running it on Windows (10) ?

**Comment by blooddrunk** [comment]
@antfu  This can be confirmed on Windows machine(Windows 11 on my use case), reverting to `0.9.5` solves the error. Although it works fine under Linux environment.

**Comment by Liwoj** [comment]
Fixed in [v0.10.1](https://github.com/antfu/unplugin-auto-import/releases/tag/v0.10.1)
Thanks!
