### ISSUE TITLE
object properties like toString broke the module

### ISSUE THREAD

**Issue by jfgodoy** [antfu/unplugin-auto-import#24]
The PR #23 introduced a bug for properties of object like `toString`.
see: https://github.com/antfu/unplugin-auto-import/blob/fad505212a3ed658f1f23b96218c991dae7e6f25/src/core/transform.ts#L57
if `name` is `toString`, will return `Object.prototype.toString` as `info`

which result in a broken import
```
import { toString } from 'undefined'
```

**Comment by liuzw2579** [comment]
I get `import { Object } from 'undefine'` in latest, 0.2.7 work success
