### ISSUE TITLE
`v0.11.0` is not published to npm

### ISSUE THREAD

**Issue by JounQin** [antfu/unplugin-auto-import#246]
### Describe the bug

As title

### Reproduction

https://unpkg.com/browse/unplugin-auto-import@0.11.0/

### System Info

```Shell
N/A
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Published. Thanks
