### ISSUE TITLE
Wrong @vueuse/core imports

### ISSUE THREAD

**Issue by bkoplin** [antfu/unplugin-auto-import#247]
Not sure if I'm doing something wrong, but it seems the @vueuse/metadata imports specify the wrong @vueuse/core exports for the @vueuse/core preset… I get a "@vueuse/core" does not export "logicOr" error.

https://github.com/antfu/unplugin-auto-import/blob/a3d830ea30b53417532ffb73a762b08f30a42da1/src/presets/vueuse-core.ts#L14-L18

**Comment by antfu** [comment]
logicOr is moved to @vueuse/math in v9.0

**Comment by bkoplin** [comment]
Thanks, I think I didn't explain myself well. The @vueuse/core preset for unplugin-auto-imports uses the @vueuse/core definitions for version 8 – **not** version 9. As such, the preset causes an error, because it tells vite that `logicOr` exports from `@vueuse/core` and not `@vueuse/math` in `auto-imports.d.ts`. Does that make sense? It's not a problem with @vueuse, it's an issue with unplugin-auto-imports…

**Comment by antfu** [comment]
Please provide a minimal production then.
