### ISSUE TITLE
How to use interface and type?

### ISSUE THREAD

**Issue by shuyuTech** [antfu/unplugin-auto-import#249]
### Describe the bug

```ts
export interface Test1 {
  name: string;
}
```

```ts
export type Test2 = {
  name: string;
}
```
How to use interface and type?

### Reproduction

none

### System Info

```Shell
System:
    OS: Linux 5.16 Fedora Linux 35 (Workstation Edition)
    CPU: (6) x64 Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
    Memory: 13.52 GB / 31.28 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shuyuTech** [comment]
I want 'interface' and 'type' to be exported in 'auto import. D.ts' like' class'

**Comment by shuyuTech** [comment]
What should I do?

**Comment by antfu** [comment]
Duplicated https://github.com/antfu/unplugin-auto-import/issues/61
