### ISSUE TITLE
Vite + @vueuse/integrations fails to only import chosen wrapper function

### ISSUE THREAD

**Issue by Ragura** [antfu/unplugin-auto-import#251]
### Describe the bug

I'm trying to use the `useChangeCase()` functions of the @vueuse/integrations package, which is a wrapper for the `change-case` package among other packages. I have installed `change-case` from npm and tried to use the auto imported VueUse function, but Vite quickly exits with an error saying all the other packages from @vueuse/integrations were not resolved.

I have set up the import in the plugin settings like this:
```
AutoImport({
      imports: [
        {
          '@vueuse/integrations': [
            'useChangeCase',
          ],
        },
      ],
    }),
```

Is there something I'm doing wrong here or have I stumbled on a bug?

### Reproduction

https://github.com/Ragura/vueuse-integrations-issue

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 92.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    npm: 8.13.1 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Use this instead:

```ts
imports: [
{
  '@vueuse/integrations/useChangeCase': [
    'useChangeCase',
  ],
},
],
```

**Comment by Ragura** [comment]
That works, don't know why I didn't think of trying that considering how you have to manually import them like that as well. Thanks for the information!
