### ISSUE TITLE
2 different version of unplugin in `yarn.lock`

### ISSUE THREAD

**Issue by minhhoanggithub** [antfu/unplugin-auto-import#252]
### Describe the bug

Two versions of `unplugin` appeared in the file `yarn.lock` after I upgraded to `unplugin-auto-import@0.11.1` , `unplugin-vue-components@0.22.4` and `vite@3.0.5 `.
This seems to make running `yarn build` very slow, about (nearly 300s).
I don't know if this is the cause of the slow build. Looking forward to your feedback. Thank you.

```
$ yarn why unplugin


yarn why v1.22.19
[1/4] Why do we have the module "unplugin"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "unplugin@0.9.0"
info Has been hoisted to "unplugin"
info Reasons this module exists
   - Hoisted from "unplugin-auto-import#unplugin"
   - Hoisted from "unplugin-vue-components#unplugin"
info Disk size without dependencies: "164KB"
info Disk size with unique dependencies: "1.08MB"
info Disk size with transitive dependencies: "1.52MB"
info Number of shared dependencies: 8
=> Found "unimport#unplugin@0.8.1"
info This module exists because "unplugin-auto-import#unimport" depends on it.
info Disk size without dependencies: "164KB"
info Disk size with unique dependencies: "1.08MB"
info Disk size with transitive dependencies: "1.52MB"
info Number of shared dependencies: 8
Done in 0.18s.
```

### Reproduction

...

### System Info

```Shell
System:
    OS: Linux 5.18 undefined
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 3.69 GB / 14.93 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.16.0 - ~/.volta/tools/image/npm/8.16.0/bin/npm
  Browsers:
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's how packages works. You can use yarn resolution to force single version before every package get updated
