### ISSUE TITLE
The name "Ref" could not be found. ts(2304)  

### ISSUE THREAD

**Issue by each1026** [antfu/unplugin-auto-import#259]
### Describe the bug

If `dts: true` is configured, it should support ts derivation, right? Is it my problem?

Checked：https://github.com/antfu/unplugin-auto-import/issues/90

I found that the method I introduced should be correct

![img](https://s2.loli.net/2022/08/28/rbhVPqADipFt6e5.png)

```ts
const count = ref(0) // not error

function changeCount(x: Ref<number>) {   // error occurred
	x.value++
}
```

```ts
// viteconfig.ts
AutoImport({
      imports: [
        'vue',
        'vue/macros',
        'vue-router',
        '@vueuse/core',
      ],
      dts: true,
      dirs: [
        './src/composables',
      ],
      vueTemplate: true,
    })
```

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "ESNext",
    "target": "es2016",
    "lib": [
      "DOM",
      "ESNext"
    ],
    "strict": true,
    "jsx": "preserve",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "allowJs": true,
    "forceConsistentCasingInFileNames": true,
    "types": [
      "vite/client",
      "vite-plugin-pages/client",
    ],
    "paths": {
      "~/*": [
        "src/*"
      ]
    }
  },
  "include": [
    "**/*.d.ts",
  ],
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

### Reproduction

1

### System Info

```Shell
vsc + mac13
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/antfu/unplugin-auto-import/issues/61
