### ISSUE TITLE
error on already imported component

### ISSUE THREAD

**Issue by jfgodoy** [antfu/unplugin-auto-import#26]
An already imported component throws an error due to double import.
seems that the regex ` /\bimport\s*([\w_$]*?),?\s*\{([\s\S]*?)\}\s*from\b/g,`  in
https://github.com/antfu/unplugin-auto-import/blob/c1d51601edd8bb4b70760e4b46a83a06c1cd11d2/src/core/transform.ts#L6
doesn't match the simple import format:
```
import IconBiX from "~icons/bi/x";
```
the part `{...}` in the regex should be optional

**Comment by antfu** [comment]
Fixed in the latest version
