### ISSUE TITLE
How to import a single file from a directory automatically

### ISSUE THREAD

**Issue by muchenfine** [antfu/unplugin-auto-import#262]
### Clear and concise description of the problem

How to import a single file from a directory automatically

### Suggested solution

How to import a single file from a directory automatically

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by v-romanyuk** [comment]
This one would be really nice to have. Is there any workaround how to achieve it?

**Comment by antfu** [comment]
Sorry I didn't got the idea. Please provide more details and examples.

**Comment by v-romanyuk** [comment]
We can put some folder path into a dirs option, which will auto import all files in that folder. So is there any possibility to auto import only 1 specific file from a folder instead of the entire folder?

**Comment by zhengyimeng** [comment]
这个功能不会实现的吗？

**Comment by Sun79** [comment]
My current solution is to create a dedicated folder for auto import, for example, ".autoimport," and then re-export all the files that need to be exported within this folder. 
![image](https://github.com/unplugin/unplugin-auto-import/assets/17243584/e6e01fbd-a9ae-41ca-9d91-e6fd9dc6754a)
![image](https://github.com/unplugin/unplugin-auto-import/assets/17243584/7909c4cc-3114-4e9f-a4aa-d63a2d3474d6)
