### ISSUE TITLE
idea: provide incremental update option to d.ts file

### ISSUE THREAD

**Issue by wiidede** [antfu/unplugin-auto-import#267]
### Clear and concise description of the problem

如果我使用了`vue-router`，也就是有异步组件，只有访问的时候，vite才会更新依赖，这时候才会更新d.ts文件。也就是说，我一开始运行vite项目时，d.ts文件中，只有异步组件用到的依赖会被去除，只有当我一个一个去访问相关页面的时候，才会更新d.ts文件。这也导致了多人合作时的问题，如果大家专注于不同的模块，自己生成的d.ts文件其实并不能概括整个项目，会导致许多冲突

If I use `vue-router`, which means that there are asynchronous components, vite will update the dependencies only when they are accessed, and that's when the d.ts file is updated. In other words, when I start running the vite project, the d.ts file, the dependencies only used by the asynchronous components are removed, and the d.ts file is only updated when I go to the relevant pages one by one. This also leads to problems when working with multiple people, if everyone focuses on different modules, their own generated d.ts file doesn't actually summarize the whole project, which can lead to a lot of conflict

### Suggested solution

如果能增量更新d.ts应该能解决这个问题，代价是如果不用某个依赖后，需要自己手动删除

If it can incrementally update d.ts, maybe this problem can be resolved, at the cost of having to manually delete a dependency yourself if you don't use it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hzgotb** [comment]
你这个问题的npm包是unplugin-auto-import还是unplugin-vue-components？

**Comment by wiidede** [comment]
> 你这个问题的npm包是unplugin-auto-import还是unplugin-vue-components？

其实都会有，你比如elementPlus，我只有在访问到用了ElMessage的页面之后，才会自动引入ElMessage（如果你的主页包括引入的文件都没有使用ElMessage）。所以这两个插件在编译的时候都没啥问题。但是如果在开发的时候，vite刚启动，这两个插件都会把当前页面所用到的东西更新到d.ts文件中，这时候你看d.ts文件，基本就是相当于删掉了很多引入。

**Comment by ll60** [comment]
> > 你这个问题的npm包是unplugin-auto-import还是unplugin-vue-components？
> 
> 其实都会有，你比如elementPlus，我只有在访问到用了ElMessage的页面之后，才会自动引入ElMessage（如果你的主页包括引入的文件都没有使用ElMessage）。所以这两个插件在编译的时候都没啥问题。但是如果在开发的时候，vite刚启动，这两个插件都会把当前页面所用到的东西更新到d.ts文件中，这时候你看d.ts文件，基本就是相当于删掉了很多引入。

老问题了，每次启动项目之后，auto-imports.d.ts就会缺少各种声明。不知道有什么好的解决方案，关掉自动生成吧，协同开发时又会出现声明没有及时更新的问题

**Comment by wiidede** [comment]
@ll60 是这样的，我现在要么就是手动维护一下d.ts，只允许它新增，要么就是把所有页面都点一遍，让d.ts都完整了再提交😅

**Comment by ll60** [comment]
> @ll60 是这样的，我现在要么就是手动维护一下d.ts，只允许它新增，要么就是把所有页面都点一遍，让d.ts都完整了再提交😅

暂时只能这样了...

**Comment by lishaobos** [comment]
参考我这个pr https://github.com/antfu/unplugin-auto-import/pull/324

**Comment by lishaobos** [comment]
options.cache 就是为了解决这个问题。

**Comment by ll60** [comment]
> options.cache 就是为了解决这个问题。

额.看了这个功能的解释..没太明白是什么意思,啥子意思: 当设置为“true”时，缓存将存储在“node_modules/.cache/unpugin auto-import.json”中。

**Comment by lishaobos** [comment]
> > options.cache 就是为了解决这个问题。
> 
> 额.看了这个功能的解释..没太明白是什么意思,啥子意思: 当设置为“true”时，缓存将存储在“node_modules/.cache/unpugin auto-import.json”中。

如果设置 true，只是你自己缓存，如果你自定义路径，允许 git 提交，这样你们就可以共享了。

**Comment by ll60** [comment]
> > > options.cache 就是为了解决这个问题。
> > 
> > 
> > 额.看了这个功能的解释..没太明白是什么意思,啥子意思: 当设置为“true”时，缓存将存储在“node_modules/.cache/unpugin auto-import.json”中。
> 
> 如果设置 true，只是你自己缓存，如果你自定义路径，允许 git 提交，这样你们就可以共享了。

🤔你说的每个字我都认识,连在一起我就有点懵逼了,自己缓存是指啥...还有哪个允许git提交指的是什么

**Comment by lishaobos** [comment]
> > > > options.cache 就是为了解决这个问题。
> > > 
> > > 
> > > 额.看了这个功能的解释..没太明白是什么意思,啥子意思: 当设置为“true”时，缓存将存储在“node_modules/.cache/unpugin auto-import.json”中。
> > 
> > 
> > 如果设置 true，只是你自己缓存，如果你自定义路径，允许 git 提交，这样你们就可以共享了。
> 
> 🤔你说的每个字我都认识,连在一起我就有点懵逼了,自己缓存是指啥...还有哪个允许git提交指的是什么

哈哈，意思就是 unplugin-auto-import 之前没有缓存，dts 是项目启动生成的，如果有些页面没有访问，dts 也就是不完整的，现在增加了缓存的功能，你们团队可以把这个缓存文件提交上去，然后每次项目启动，都会根据缓存生成 dts.

**Comment by ll60** [comment]
> 

大致明白了,有空试试,谢谢解答🙏

**Comment by ll60** [comment]
> > > > > options.cache 就是为了解决这个问题。
> > > > 
> > > > 
> > > > 额.看了这个功能的解释..没太明白是什么意思,啥子意思: 当设置为“true”时，缓存将存储在“node_modules/.cache/unpugin auto-import.json”中。
> > > 
> > > 
> > > 如果设置 true，只是你自己缓存，如果你自定义路径，允许 git 提交，这样你们就可以共享了。
> > 
> > 
> > 🤔你说的每个字我都认识,连在一起我就有点懵逼了,自己缓存是指啥...还有哪个允许git提交指的是什么
> 
> 哈哈，意思就是 unplugin-auto-import 之前没有缓存，dts 是项目启动生成的，如果有些页面没有访问，dts 也就是不完整的，现在增加了缓存的功能，你们团队可以把这个缓存文件提交上去，然后每次项目启动，都会根据缓存生成 dts.

大致明白了,有空试试,谢谢解答🙏

**Comment by wiidede** [comment]
大致明白了,有空试试,谢谢解答🙏大佬顺便啥时候给unplugin-vue-components整一个 @lishaobos

**Comment by lishaobos** [comment]
> 大致明白了,有空试试,谢谢解答🙏大佬顺便啥时候给unplugin-vue-components整一个 @lishaobos

大佬不敢，就这两天吧，也同步过去。

**Comment by wiidede** [comment]
原来有两个pr，还有这个 https://github.com/antfu/unplugin-auto-import/pull/311 ，辛苦大佬的贡献🥰~~顺便种草了你的magic-image~~

**Comment by lishaobos** [comment]
> 原来有两个pr，还有这个 #311 ，辛苦大佬的贡献🥰~顺便种草了你的magic-image~

感谢感谢😄😄😄
