### ISSUE TITLE
In vite ,how to use component  to show autoimported unplugin-icons

### ISSUE THREAD

**Issue by xingshuyin** [antfu/unplugin-auto-import#275]
in vite,  i wang to auto import unplugin-icons like  `<component is='ep:eleme-filled'></component>`
but is not work  i can only use like that
` <ep:eleme-filled style="font-size: 20px; color: beige;" />`

so does that a method  use component  to show the icon?

**Comment by qmhc** [comment]
I have a similar case and want to use icon components via a prop, but now it seems not support this usage (although set `vueTemplate: true`).

**Comment by qmhc** [comment]
@azaleta Sry, I should have clarified. It still needs to set `imports` after `vueTemplate: true`, it seems cannot use a resolver to instead `imports` setting.

```ts
// Can I using a resolver to replace the `imports`?
// Currently it seems not trigger the resolve method in resolver
AutoImport({
  vueTemplate: true,
  imports: [
    {
      'icons-lib': Object.keys(await import('icons-lib'))
    }
  ]
})
```

```html
<!-- A usage like this -->
<Icon :svg="active ? ArrowLeft ? ArrowDown"></Icon>
```

**Comment by azaleta** [comment]
Yes. that's the solution in the past issue. :)
![image](https://user-images.githubusercontent.com/22554452/194236171-f96820c1-7b7d-4f08-9761-4b61106f9c35.png)
