### ISSUE TITLE
How about a @vueuse/shared preset?

### ISSUE THREAD

**Issue by chrisbbreuer** [antfu/unplugin-auto-import#276]
### Clear and concise description of the problem

I am currently in the process of developing a "full stack framework" and I find it very useful to automatically have access to utilities like `isString()` & `isNumber()`, amongst others.

I am wondering whether there is a specific reason the preset does not yet exist (something obvious I am not seeing) or if there would be an interest in getting support for it?

### Suggested solution

The solution would be to create a `@vueuse/shared` preset.

### Alternative

One can also be explicit as I am in this case:

https://github.com/stacksjs/stacks/blob/main/.stacks/core/stacks.ts#L25

The `vitest` preset does include an `assert` method as well, so that's the only clash there was.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by azaleta** [comment]
@vueuse/shared is included in @vueuse/core preset.
https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/vueuse-core.ts#L28

**Comment by antfu** [comment]
@vueuse/shared are not designed to be generally used. And `isXX` is an internal helper that maybe not be used directly (it might break without semver)

**Comment by chrisbbreuer** [comment]
Ah got it! I just noticed some of those helpers were missing which generally have been pretty useful on my end. Thanks for the clarification!
