### ISSUE TITLE
Not working properly when using ternary operator

### ISSUE THREAD

**Issue by threedayAAAAA** [antfu/unplugin-auto-import#279]
### Describe the bug

Not working properly when using ternary operator

### Reproduction

Not working properly when using ternary operator

```js
{
    vueTemplate: true,
    imports: [
      'vue',
      'vue-router',
      {
        '@sxf/util/uuid': ['uuid'],
      },
    ],
    eslintrc: {
      enabled: true,
      filepath: './.eslintrc-auto-import.json',
      globalsPropValue: true,
    },
    dirs: [
      './util/**',
    ],
    dts: '../../types/auto-imports.d.ts',
  }
```

```js
// util/config.ts
export const data = 1
```

```js
// main.ts
const a = Math.random() > 0.5 ? data : 2
```

### System Info

```Shell
"unplugin-auto-import": "^0.11.2",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
It works fine.
Does you config.ts is in `src/util`?
```
 dirs: [
   './src/composables',
   './src/util',
 ],
```

![image](https://user-images.githubusercontent.com/22554452/195751608-11f0799e-ee71-475c-b4c6-b84a3a5def9e.png)
![image](https://user-images.githubusercontent.com/22554452/195751663-866b3183-7ddf-4146-a658-d4afd8d28993.png)
![image](https://user-images.githubusercontent.com/22554452/195751720-545c96ae-e289-45e3-98f2-f1178e9f756b.png)

**Comment by threedayAAAAA** [comment]
> It works fine. Does you config.ts is in `src/util`? Pls check your auto-imports.d.ts if the `data` has been check->imported
> 
> ```
>  dirs: [
>    './src/composables',
>    './src/util',
>  ],
> ```
> 
> ![image](https://user-images.githubusercontent.com/22554452/195751608-11f0799e-ee71-475c-b4c6-b84a3a5def9e.png) ![image](https://user-images.githubusercontent.com/22554452/195751663-866b3183-7ddf-4146-a658-d4afd8d28993.png) ![image](https://user-images.githubusercontent.com/22554452/195751720-545c96ae-e289-45e3-98f2-f1178e9f756b.png)

You can check the reproduction link

https://codesandbox.io/s/elastic-bose-ok23h3?file=/src/main.ts


![image](https://user-images.githubusercontent.com/38604634/197233406-642b00d8-fd69-4e8b-9953-8290d4ab60d5.png)

**Comment by azaleta** [comment]
Please add `auto-imports.d.ts` to your tsconfig
![image](https://user-images.githubusercontent.com/22554452/197303727-1b39ee8b-d42f-4ac1-9734-b4063e8435a8.png)

![image](https://user-images.githubusercontent.com/22554452/197303672-d37340e1-f90d-4a58-b59a-32629ad5bcd6.png)
![image](https://user-images.githubusercontent.com/22554452/197303763-9adbbc35-18d0-4e27-82cf-ded4d0aa55c0.png)

**Comment by threedayAAAAA** [comment]
> Please add `auto-imports.d.ts` to your tsconfig ![image](https://user-images.githubusercontent.com/22554452/197303727-1b39ee8b-d42f-4ac1-9734-b4063e8435a8.png)
> 
> ![image](https://user-images.githubusercontent.com/22554452/197303672-d37340e1-f90d-4a58-b59a-32629ad5bcd6.png) ![image](https://user-images.githubusercontent.com/22554452/197303763-9adbbc35-18d0-4e27-82cf-ded4d0aa55c0.png)

Seems like I'm providing a wrong use case. An error is reported when the ternary operator gets the value of auto-import. For example the picture below

![image](https://user-images.githubusercontent.com/38604634/197429073-197b268c-a3dd-46cc-9ea4-fccb58a79e69.png)

![image](https://user-images.githubusercontent.com/38604634/197429086-72971d4a-f648-45a6-ba7d-00d5c33e4369.png)
