### ISSUE TITLE
useless import in monorepo

### ISSUE THREAD

**Issue by LarchLiu** [antfu/unplugin-auto-import#281]
### Clear and concise description of the problem

- If some packages in the monorepo compiled out the same variable as `plugin` imported(such as `h` that imported from `vue`), when i use this packages as `workspace` `plugin` will import this variable too and cause error.

```
Uncaught SyntaxError: Identifier 'h' has already been declared
```

![WX20221014-111220](https://user-images.githubusercontent.com/4410452/195753830-c4a6ca76-bb8b-4deb-a4a3-763f53ade6f4.png)

Although i can set `exclude` those packages, but i donot know which package will compiled out `h` or something that imported by `plugin` unless i got error.
```
exclude: [/node_modules/, /\.git/, /core\/pinia/, /ui\/block-plugin-template/],
```

- if i want auto import `@poto/pinia` like this
```
AutoImport({
      imports: [
        'vue',
        '@vueuse/core',
        'pinia',
        {
          '@poto/pinia': [
            'useActionsStore',
            'useCustomBlocksStore',
            'useDesignerStore',
            'useWidgetMenuStore',
          ],
        },
      ],
      dts: 'src/auto-imports.d.ts',
      vueTemplate: true,
      resolvers: [ElementPlusResolver()],
      exclude: [/node_modules/, /\.git/, /ui\/block-plugin-template/],
    }),
```
`plugin` will import itself to this package
![WX20221014-113928](https://user-images.githubusercontent.com/4410452/195757071-17b9d52e-dd4f-4694-8401-85044e3eb3b0.png)

### Suggested solution

Maybe `transform` should have a `dynamic filter`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by azaleta** [comment]
https://github.com/antfu/unplugin-auto-import/blob/2c37ab86fcfda773be366a97e2967a9790a63bf8/src/types.ts#L117-L121

**Comment by LarchLiu** [comment]
> https://github.com/antfu/unplugin-auto-import/blob/2c37ab86fcfda773be366a97e2967a9790a63bf8/src/types.ts#L117-L121

This should not be the reason. This issues is about the filter of transform

**Comment by LarchLiu** [comment]
I got it, should `exclude` anything out of project.

```
exclude: [/node_modules/, /\.git/, /^(?!.*ui\/playground\/)/],
```
