### ISSUE TITLE
[APPRECIATION] Appreciation Thread and Tip For New Comers About auto-imports.d.ts File

### ISSUE THREAD

**Issue by angelhdzmultimedia** [antfu/unplugin-auto-import#285]
I was about to post a new issue beause even though the package worked right away after carefully following the instructions, and the app compiled in the browser, TypeScript or Volar was complaining about not finding the elements, **and then it hit me:**
I had to include the `auto-imports.d.ts` file in the include array in the `tsconfig.json`, the same way I did with unplugin-vue-router and vite-plugin-vue-layouts.

**So for newcomers,** after running the app for first time to generate the auto-imports.d.ts, don't forget to include it
in the tsconfig.json.

### Appreciation Thread
Didn't find the Discussions tab, so I'm opening an Issue instead, I hope not causing any inconvenience.

My main intention with this thread is to give the team a big appreciation for all the hard work they have been doing in the Vue ecosystem. All this excites me and I'm experimenting with all this every day. Seeing the modules automatically imported
and being able to hover the imported elements and see their definition feels magical.

I experienced this in Nuxt 3, but being able to have it in a pure Vue 3 project is amazing.
And of course I will promote this library in my YouTube videos and will add a tutorial in the upcoming weeks.
I will keep playing with `slidevjs` as well.

So, again, thank you guys a lot for these amazing, magical, and fun libraries, and for the kind and encouraging maintainers that 
give us a hand when we are pulling our hairs off in desperation. ☺🔥🤯👋🤝😍

**Comment by antfu** [comment]
Thank you. We could add a FAQ section to mention about this, PR welcome :)

**Comment by angelhdzmultimedia** [comment]
> Thank you. We could add a FAQ section to mention about this, PR welcome :)

Today I was about to contribute with a PR, but decided to recheck the guide for last time, and then I noticed this:

![image](https://user-images.githubusercontent.com/10191085/198505859-14965b13-2f94-47e0-bebf-d7d309f68d1b.png)

Basically, the instructions are there, but in reverse! That's why it went over my head!
It should say "Make sure to include `auto-imports.d.ts` in tsconfig.json" otherwise it implies that it gets automatically included, and we need to check if we aren't explicitly excluding it... 

All in all, everything it's amazing now. 😊🔥🤝
