### ISSUE TITLE
Self referencing `import` statement generated

### ISSUE THREAD

**Issue by bkrypt** [antfu/unplugin-auto-import#287]
### Describe the bug

I use this package in a Vite/Vue3 project, and since `v0.11.4` I've encountered this issue where one of my utility import files, in this case dealing with `window`, is generating a self referencing `import` statement within itself in dev builds.

Below is the output of what I see in the `Sources` section of the browser dev tools for the particular file in question.

- **v0.11.4 (window.ts)**
```
import window from '/src/imports/window.ts';
export default typeof window !== "undefined" ? window : globalThis;
```

- **<= v0.11.3 (window.ts)**
```
export default typeof window !== "undefined" ? window : globalThis;
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xlbot7?file=src/App.vue

### System Info

```Shell
System:
  OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  CPU: (5) arm64 unknown
  Memory: 368.61 MB / 1.94 GB
  Container: Yes
  Shell: 5.1.4 - /bin/bash
Binaries:
  Node: 16.18.0 - /usr/bin/node
  npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tvld** [comment]
Same here, I think?:
Error:
``Uncaught SyntaxError: Identifier 'User' has already been declared (at users.st.ts:4:8)``

```js

// file: /src/stores/users.st.ts
import { User } from '/src/stores/users.st.ts';  // gives error: this line is generated by unplug, it  import itself !
import { defineStore, BaseModel } from "/src/plugins/pinia.ts";
import { api } from "/src/feathers.ts";
export class User extends BaseModel {
}
const servicePath = "users";
export const useUsers = defineStore({
  servicePath,
  Model: User
});
api.service(servicePath).hooks({});

```
