### ISSUE TITLE
I want to add auto-imports.d.ts to gitignore, but the production environment will report an error

### ISSUE THREAD

**Issue by sky124380729** [antfu/unplugin-auto-import#288]
### Clear and concise description of the problem

Hmm, 

If you don't add auto-imports.d.ts to gitignore, it will change frequently and cause conflicts, so I want to add gitignore, but this will cause another problem. The production environment does not have this d.ts file, and execute vue-tsc When an error occurs, how should I configure it?

![image](https://user-images.githubusercontent.com/23203328/198970397-0b1cdab7-b797-4ebc-a1f9-9cd6396cb455.png)

### Suggested solution

i don't know

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by dev-vinicius-andrade** [comment]
any news regarding this? I'm experiencing the same problem. I've added the auto-imports.d.ts  to gitignore, but know the build doesn't work if i don't run vite --host --port 5050

**Comment by dev-vinicius-andrade** [comment]
I don't know if you have already tried to do this. But i inverted the order of my script
** before ** 
`"vue-tsc --noEmit && vite build"`

** after** 
`"vite build && vue-tsc --noEmit"`

Now it's generating the auto-imports.d.ts and the errors disapear

**Comment by sky124380729** [comment]
i think if you do `vite build` first , `vue-tsc --noEmit` doesn't make sense anymore

**Comment by dev-vinicius-andrade** [comment]
At least it will capture some typescript problems, that are not related to the auto imports. I don't think this is the rigth way to do it, but it's a work around till some  answers...

**Comment by antfu** [comment]
It's recommended to commit the file. Otherwise, you should run the build before typechecking.

**Comment by JJiangZhe** [comment]
我也碰到这个问题

**Comment by fukai007** [comment]
@JJiangZhe  
1  你先在运行时跑通  确保 json  和  x.d.ts  你需要的都写入
2   关闭 dts  和  eslintrc 配置     
3   重新build 你的项目就OK
```
 // Filepath to generate corresponding .d.ts file.
  // Defaults to './auto-imports.d.ts' when `typescript` is installed locally.
  // Set `false` to disable.
  dts: false,


  // Generate corresponding .eslintrc-auto-import.json file.
  // eslint globals Docs - https://eslint.org/docs/user-guide/configuring/language-options#specifying-globals
  eslintrc: {
    enabled: false, 
    filepath: './.eslintrc-auto-import.json', // Default `./.eslintrc-auto-import.json`
    globalsPropValue: true, // Default `true`, (true | false | 'readonly' | 'readable' | 'writable' | 'writeable')
  },
```
原因分析(未读源码) :   全量覆盖 没有做到智能覆盖,存在的就不覆盖

**Comment by dev-vinicius-andrade** [comment]
@fukai007 as I said before, I think the best way to handle it, since the way the plugin works, is to run build before checking tsc.

**Comment by srchafreenn** [comment]
I'm experiencing the same problem.

**Comment by so1ve** [comment]
@srchafreenn Just commit the file. If you don't do so, once new developers clone your repository they should run the build step first to avoid type errors.

**Comment by zeakey** [comment]
> It's recommended to commit the file. Otherwise, you should run the build before typechecking.

Sounds weird to commit a auto-generated file to version control.

**Comment by ZacharyBear** [comment]
> Why no, `unplugin-vue-components` support generated.为什么不，生成`了 unplugin-vue-components` 支持。

In my opinion, a generated file shouldn't be commited. Every participants could generate an differently result, this makes conflicts happen easier.
