### ISSUE TITLE
Variables prefixed with `$` are not auto-imported when used in template

### ISSUE THREAD

**Issue by hymair** [antfu/unplugin-auto-import#290]
### Describe the bug

I am auto-importing my `~/composables` folder, but exporting variables with name starting with "$" is not working when used directly in the template. `vueTemplate` option is enabled.

```
[Vue warn]: Property "$test" was accessed during render but is not defined on instance.
```

### Reproduction

https://stackblitz.com/edit/vue3-vite-typescript-starter-3nepur?file=src/App.vue

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.79 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
https://github.com/unjs/unimport/pull/140

**Comment by antfu** [comment]
https://github.com/unjs/unimport/pull/140#issuecomment-1306675549
