### ISSUE TITLE
不支持自动引入 vue-router 的  `createRouter` `createWebHistory` 等

### ISSUE THREAD

**Issue by KeyToLove** [antfu/unplugin-auto-import#292]
https://github.com/antfu/unplugin-auto-import/blob/b2a5a65995e354a51b446694b77560dd8b3e2784/src/presets/vue-router.ts#L3-L11
如题，vue-router的presets中仅支持部分的自动引入，是刻意为之或者其它原因吗？

**Comment by azaleta** [comment]
https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#360-2022-08-22
check v3.6.0 release note

**Comment by KeyToLove** [comment]
> https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#360-2022-08-22 check v3.6.0 release note

这似乎与我遇到的问题没直接联系，可能是我没表述清楚，我再说明一下：
我的项目是通过 `pnpm create vite xxx --template vue`创建("vue-router": "^4.1.2")，使用`unplugin-auto-import`期望帮我处理自动引入

![image](https://user-images.githubusercontent.com/54970106/202097649-b23db663-737e-44de-8e38-a0aabe0724eb.png)

![image](https://user-images.githubusercontent.com/54970106/202097758-9148788d-e117-476d-a07c-748750cc5980.png)
如上图所示，`useRoute` is ok，`createRouter`仍需要显式的引入
我想弄清楚的是`unplugin-auto-import`仅支持`useRouter `、`useRoute `、`useLink `、`onBeforeRouteLeave `、`onBeforeRouteUpdate `的原因。

**Comment by azaleta** [comment]
?
did you check the doc?
https://github.com/vuejs/vue-router/blob/dev/CHANGELOG.md#360-2022-08-22

**Comment by azaleta** [comment]
yes :)
you can expand `preset` by config if you are using V4
Happy coding.
