### ISSUE TITLE
import { Vue } from 'vue-property-decorator' is invalid

### ISSUE THREAD

**Issue by GenesisLQ** [antfu/unplugin-auto-import#301]
### Describe the bug

<img width="746" alt="image" src="https://user-images.githubusercontent.com/48673814/206105157-bce89e59-b0d1-4be9-9051-5d43bcd492e4.png">
<img width="982" alt="image" src="https://user-images.githubusercontent.com/48673814/206105730-9e9c4e44-a757-4b17-ac24-a7ba2ba419ff.png">

我们用的 vue2 + class 的写法，在 webpack 里面同样的配置可以使用，但是 vite 不行，除了 Vue 以外所有的都可以自动导入，应该怎么解决这个问题？

versions: 
vue: 2.7.4
vue-class-component: 7.2.6
vue-property-decorator: 9.1.2

### Reproduction

https://github.com/GenesisLQ/unplugin-auto-import_Vue

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 33.09 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sabasayer** [comment]
I think it is related with class components extending something. 
I have an example that i am extending from some mixin and it is also not included in the build.
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/45066901/221358018-9289b828-0fc5-4c11-97fb-1c13692b500f.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/45066901/221358023-800990b5-e996-4ce5-9aff-397f9c958f1a.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/45066901/221358035-66be8152-da0f-40ac-a936-efbf61c2768d.png">

Here you can see there is no BaseMixin imported from @comed/common-vue: 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/45066901/221358067-3d30cac0-2732-4b11-9dc1-df6e0e8dc38f.png">

**Comment by so1ve** [comment]
I believe this is an unimport issue, let's track in unjs/unimport/issues/243
