### ISSUE TITLE
Does this plug-in support automatic import of style files, such as `import './ style.css'`?

### ISSUE THREAD

**Issue by didengren** [antfu/unplugin-auto-import#313]
### Clear and concise description of the problem

Does this plug-in support automatic import of style files, such as `import './ style.css'`?

### Suggested solution

Hope to be able to set the import path in the options, just like:
```js
{
  path: '/dist/style.css'
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
Can vite alias meet your needs?

**Comment by antfu** [comment]
No, this is out-of-scope.
