### ISSUE TITLE
[DX] Avoid warning when not needed

### ISSUE THREAD

**Issue by ennioVisco** [antfu/unplugin-auto-import#314]
### Describe the bug

Ideally, this line should be printed only when the output has no imports, but it is printed anytime `Options.imports` is empty (but users could instead be importing with `Options.include` or `Options.dirs`.

Also, the English could be polished a bit and changed [here](https://github.com/antfu/unplugin-auto-import/blob/270ea17b3a1e7de6e9d64d1f31ea3e1bee91572a/src/core/ctx.ts#L150) to: 
[auto-import] plugin installed but no imports ~has~**have been** defined, see https://github.com/antfu/unplugin-auto-import#configurations for configurations'

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ascott18** [comment]
Additionally, the #configurations anchor doesn't exist - it should be #configuration (no `s`)
