### ISSUE TITLE
eslint无法自动修复vue/no-ref-as-operand

### ISSUE THREAD

**Issue by LetFree** [antfu/unplugin-auto-import#317]
### Describe the bug

vite vue3 setup ref 定义的变量，使用时，遗忘

> .value

eslint 不会报错也无法自动修复

### Reproduction

vite vue3 setup

### System Info

```Shell
none
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is considered out-of-scope to the project. Thanks for bringing it up. Closing.

**Comment by LetFree** [comment]
> This is considered out-of-scope to the project. Thanks for bringing it up. Closing.

大佬劳动节快乐，弱弱的问一句，这个问题还有计划解决吗（是要从eslint那边起手解决吗？）

**Comment by Miofly** [comment]
this problem what should be done
