### ISSUE TITLE
Resolve aliases arent resolved

### ISSUE THREAD

**Issue by silentmantra** [antfu/unplugin-auto-import#337]
### Describe the bug

I created an alias to an external folder.
Works fine in code, but seems the auto import doesnt resolve it.
Also the absense of an error due of unabling to identify an existing folder makes the error obscure, like described here: 
https://github.com/antfu/unplugin-vue-components/issues/609
the same bug happens in `unplugin-vue-components` - no aliases are resolved.
that's a big problem because it's impossible to use the auto import and vue components universally in the both
`project` and `frontend` directories because the relative path `../../../frontend` is resolved differently and doesnt work in the `frontend` directory
```
export default defineConfig(({ command, mode, ssrBuild }) => ({
    resolve: {
        alias: {
            '@common': fileURLToPath(new URL('../frontend', import.meta.url)),
        }
    },
    plugins: [
        vue(),
        Components({
            dirs: ['.', '../../../frontend/components'],
            extensions: ['vue'],
        }),
        AutoImport({
            imports: [
                'vue',
                'vue-router',
                {
                    'vue-i18n': ['useI18n'],
                    'axios': [['default', 'axios']],
                    '@common/utils': ['useModel'],
                }
            ],
```

### Reproduction

Provide an alias to an external folder in the imports option

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel Xeon Processor (Icelake)
    Memory: 607.58 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.21.3 - /usr/local/bin/node
    npm: 6.14.18 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
it is a good point, i think the feature requires the author @antfu to see if it is necessary.
