### ISSUE TITLE
Webstorm中自动导入的组合式API的类型提示有问题。

### ISSUE THREAD

**Issue by wastelandEmperor** [antfu/unplugin-auto-import#340]
### Describe the bug

![Snipaste_2023-03-07_21-09-56](https://user-images.githubusercontent.com/96726103/223431555-4bb720a6-c799-4aee-8b1d-23abd3d6b33c.PNG)

![image](https://user-images.githubusercontent.com/96726103/223431731-800e6b38-bfed-4b9b-985b-7f865baf96b7.png)

### Reproduction

无

### System Info

```Shell
windows11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chengshaohui** [comment]
I also encountered the same problem, hope to solve

**Comment by antfu** [comment]
I don't think this has something to do with this project
