### ISSUE TITLE
我希望支持依赖库的CDN引入特性

### ISSUE THREAD

**Issue by Min888888** [antfu/unplugin-auto-import#345]
### Clear and concise description of the problem

我使用vite4+vue3开发项目，也使用了我们的自动引入插件，在项目结束时我希望进行一次CDN优化，可是我无法改变unplugin打包后的依赖名字

### Suggested solution

我希望可以在配置时进行升级
autoImport: {
  // ...
  imports: [
    // ...
    {
      vue: {
        // 禁用自动引入
        disabled: true,
        // 手动引入全局 Vue
        // 这里假设你使用的是全局引入版本的 Vue
        default: 'Vue',
        path: 'https://cdnjs.cloudflare.com/ajax/libs/vue/3.2.45/vue.global.prod.min.js',
      },
    },
  ],
}

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
我觉得这个不属于插件的范畴，属于 vite 打包，你可以看下这个 https://github.com/vitejs/vite/discussions/3744

**Comment by antfu** [comment]
There is no plan to support CDN packages. You may use other plugins.
