### ISSUE TITLE
能否对vue-request框架支持预设

### ISSUE THREAD

**Issue by enjoy-wind** [antfu/unplugin-auto-import#346]
### Clear and concise description of the problem

vue-reuqest自定义预设报错

### Suggested solution

自定义预设是否可以让用户自己选择，毕竟如果想自定义预设，对于自动导入的概念已经有很深的理解了，基本能正确使用，所以github.1K+的设定没有必要去做。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
你好，没理解你的意思，可以再详细描述下，或者提供可复现的 git 仓库吗？

**Comment by lishaobos** [comment]
嗯，这个插件的机制是这样的，imports 里面写的是预置的插件，但是 vue-request 是不在 preset 里面的，所以可以直接使用 resolver:

```js
resolvers: [
        (name) => {
          const customHookMap = {
            'vue-request': ['useRequest'],
          }
          for (const key of Object.keys(customHookMap)) {
            const valList = customHookMap[key as keyof typeof customHookMap]
            if (valList.includes(name)) {
              return {
                name,
                from: key,
              }
            }
          }
        },
      ],

imports: [
          // 'vue-request': ['useRequest'],

]
```

**Comment by antfu** [comment]
We no longer accept new presets. Thanks

**Comment by enjoy-wind** [comment]
thanks,现在已经支持自定义，但是我理解错了
