### ISSUE TITLE
First line Commented 'import' statement caused 'Module parse failed'

### ISSUE THREAD

**Issue by xiaofuyesnew** [antfu/unplugin-auto-import#350]
### Describe the bug

In the vue3 with webpack setup-script:
If this first line is `commented` import statement can cause an error of 'Module parse failed: 'import' and 'export' may only appear at the top level'.

throw error:
```vue
<script setup>
// import { ref } from 'vue'      -->  not only import from vue, but also the other lib
import Hello from '../components/Hello.vue'

const test = ref(0)
</script>
```

Any of the following will `NOT` cause an error：
```vue
<script setup>
// import { ref } from 'vue           -->  incomplete import statement
import Hello from '../components/Hello.vue'
// import { ref } from 'vue'          -->  not at the first line

const test = ref(0)
</script>
```

### Reproduction

https://github.com/xiaofuyesnew/reproductions/tree/main/auto-import-issues

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 19.63 GB / 31.65 GB
  Binaries:
    Node: 19.8.1 - ~\.nvs\default\node.EXE
    Yarn: 1.22.19 - ~\.npm_global\yarn.CMD
    npm: 9.6.2 - ~\.npm_global\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.51)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GGBeng1** [comment]
The same problem, trouble for a long time to find 😭

**Comment by ihwf** [comment]
same problem

**Comment by ihwf** [comment]
resolve, add option `injectAtEnd: false`

**Comment by xiaofuyesnew** [comment]
> resolve, add option `injectAtEnd: false`

```javascript
// webpack.config.js
import AutoImport from 'unplugin-auto-import/webpack'

export default {
  ...,
  plugins: [
    ...,
    AutoImport({
      ...,
      injectAtEnd: false  // add this, done!🚀
    })
  ]
}
```

Thanks, dude!
