### ISSUE TITLE
自动导入的api无法正确推导类型

### ISSUE THREAD

**Issue by JohnnyTang-D** [antfu/unplugin-auto-import#354]
### Describe the bug

这是我的示例代码,在webstorm上会飘红,显示类型unknown.

![image](https://user-images.githubusercontent.com/49517935/229011030-fa689f95-705b-4c57-81cc-3322d0761569.png)

### Reproduction

none

### System Info

```Shell
ts版本:4.9.5
node:14.18.0
elementPlus:2.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by tangxiangmin** [comment]
这个应该是webstorm的问题，根据[youtrack论坛反馈](https://youtrack.jetbrains.com/issue/WEB-56524/The-types-of-refs-in-templates-are-unknown-when-using-auto-import-plugin)，将在webstorm2023.1.1的版本中修复，这个版本目前应该还没有发布，需要等一会

**Comment by JohnnyTang-D** [comment]
感谢 感谢  我用vscode确实没有发现.只有最新版webstorm会出现

**Comment by AkenClub** [comment]
刚发现用pnpm时候会识别成any，用npm/yarn时候，ref 是能在模板中识别出类型的，但是reactive还是不行
![image](https://github.com/antfu/unplugin-auto-import/assets/52781316/2a2e4744-c261-444b-8fa9-b59c868cc043)

**Comment by JohnnyTang-D** [comment]
> 刚发现用pnpm时候会识别成any，用npm/yarn时候，ref 是能在模板中识别出类型的，但是reactive还是不行 ![image](https://user-images.githubusercontent.com/52781316/240822845-2a2e4744-c261-444b-8fa9-b59c868cc043.png)



> 刚发现用pnpm时候会识别成any，用npm/yarn时候，ref 是能在模板中识别出类型的，但是reactive还是不行 ![image](https://user-images.githubusercontent.com/52781316/240822845-2a2e4744-c261-444b-8fa9-b59c868cc043.png)

我刚才也试了下,确实是pnpm的问题,换成yarn就可以了.我现在是最新版的webstorm

**Comment by JohnnyTang-D** [comment]
> 刚发现用pnpm时候会识别成any，用npm/yarn时候，ref 是能在模板中识别出类型的，但是reactive还是不行 !

刚才我升级pnpm到8.6版本 类型推导已经没有问题了

**Comment by AkenClub** [comment]
> 刚才我升级pnpm到8.6版本 类型推导已经没有问题了

我刚也升级到8.6了，在script中类型推导是可以的，但是在template还是unknow
![image](https://github.com/antfu/unplugin-auto-import/assets/52781316/d6e091df-d505-4234-9d66-7fcd6f667ac6)

**Comment by JohnnyTang-D** [comment]
> > 刚才我升级pnpm到8.6版本 类型推导已经没有问题了
> 
> 我刚也升级到8.6了，在script中类型推导是可以的，但是在template还是unknow 

webstorm是最新的吗 '内部版本号 #WS-231.9011.35，2023年5月16日 构建'

**Comment by JohnnyTang-D** [comment]
> > > > 刚才我升级pnpm到8.6版本 类型推导已经没有问题了
> > > 
> > > 
> > > 我刚也升级到8.6了，在script中类型推导是可以的，但是在template还是unknow
> > 
> > 
> > webstorm是最新的吗 '内部版本号 #WS-231.9011.35，2023年5月16日 构建'
> 
> 和你版本一样，如果导入 ref reactive 的话就能正常推导的，和[youtrack](https://youtrack.jetbrains.com/issue/WEB-56524/The-types-of-refs-in-templates-are-unknown-when-using-auto-import-plugin)里面说的bug一样情况。你升级pnpm之后不用导入 reactive 都能推导了？

对的.我就是删掉node_modules之后,全局执行 npm add pnpm -g之后,然后删掉lock文件,重新pnpm i然后就好了.我用的是vite

**Comment by oyal** [comment]
我试了还是不行
Webstorm：内部版本号 #WS-231.9011.35，2023年5月16日 构建
pnpm：8.6.0
删了node_modules和lock重装依赖还这样，也是Vite项目

![image](https://github.com/antfu/unplugin-auto-import/assets/88022434/6c096dc1-7fb0-4e8c-a13c-5e1e93f97250)

**Comment by AkenClub** [comment]
> > > > > 刚才我升级pnpm到8.6版本 类型推导已经没有问题了
> > > > 
> > > > 
> > > > 我刚也升级到8.6了，在script中类型推导是可以的，但是在template还是unknow
> > > 
> > > 
> > > webstorm是最新的吗 '内部版本号 #WS-231.9011.35，2023年5月16日 构建'
> > 
> > 
> > 和你版本一样，如果导入 ref reactive 的话就能正常推导的，和[youtrack](https://youtrack.jetbrains.com/issue/WEB-56524/The-types-of-refs-in-templates-are-unknown-when-using-auto-import-plugin)里面说的bug一样情况。你升级pnpm之后不用导入 reactive 都能推导了？
> 
> 对的.我就是删掉node_modules之后,全局执行 npm add pnpm -g之后,然后删掉lock文件,重新pnpm i然后就好了.我用的是vite

我的还是不行

**Comment by AkenClub** [comment]
> 我试了还是不行 Webstorm：内部版本号 #WS-231.9011.35，2023年5月16日 构建 pnpm：8.6.0 删了node_modules和lock重装依赖还这样，也是Vite项目
> 
> ![image](https://user-images.githubusercontent.com/88022434/241879593-6c096dc1-7fb0-4e8c-a13c-5e1e93f97250.png)

同

**Comment by AkenClub** [comment]
> 我也是同样的问题，但是删除用pnpm i后类型变成any了，这貌似不对吧 ![image](https://user-images.githubusercontent.com/46436708/242945324-95f48b84-80d6-4bc8-bb57-3f29f030be45.png)

我也出现过 any 的情况，之后删除 node_module 重新 install 一下就好了

**Comment by oyal** [comment]
> 这个应该是webstorm的问题，根据[youtrack论坛反馈](https://youtrack.jetbrains.com/issue/WEB-56524/The-types-of-refs-in-templates-are-unknown-when-using-auto-import-plugin)，将在webstorm2023.1.1的版本中修复，这个版本目前应该还没有发布，需要等一会

这个问题应该已经修复了
