### ISSUE TITLE
Arco Resolver options增加exclude选项

### ISSUE THREAD

**Issue by shaoerkuai** [antfu/unplugin-auto-import#358]
### Describe the bug

我有一个API封装的组件，因为开头是A，内部命名触发了ArcoResolver的规则，导致被错误import了
![image](https://user-images.githubusercontent.com/117460332/230760223-65793d6c-900e-4745-b516-fdd77458f8f3.png)
希望Arco Resolver支持exclude，把我自己A开头组件给排除掉。目前只能在自己的代码里暂时改成别的名字实现。

### Reproduction

custom A-prefix ts moudle import

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 45.10 GB / 63.80 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by l1uqi** [comment]
antfu/unplugin-vue-components#621
