### ISSUE TITLE
关于ts的类型推导在idea上使用效果不理想

### ISSUE THREAD

**Issue by GaoJuqian** [antfu/unplugin-auto-import#373]
当使用自动导入时的效果
<img width="983" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/46cf4b19-b1f3-4122-8795-42ebb9bacb18">

---

<img width="836" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/ceb72fa9-30e2-48d2-ba51-99c50bae3cbc">

---

<img width="813" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/4fa271e4-2f70-4414-9b2c-aeb0c92397b5">

---

当手动导入时的效果

<img width="1070" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/1bc6cba0-754c-4d7e-b29a-84369d38b681">

---

<img width="975" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/0af47c61-bf15-4c24-9344-e44cdf71b25f">

---

<img width="1069" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/178e259e-d174-47b1-80b9-2bf210a19f5a">

---

当我在vscode使用自动导入时的理想效果

<img width="829" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/55aea216-49c0-4bd6-a22c-24f57bf89adc">

---

<img width="805" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/2bab753a-828b-412f-b788-3951a0e667c6">

---

是否因为这个插件

<img width="1552" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/50407511/1f24696d-3dc6-44c0-b20b-82fe19b7426f">

**Comment by so1ve** [comment]
你得去问jetbrains

**Comment by antfu** [comment]
It's not related to the extension. I think it's JetBrains' implementation issue. There is nothing we could do about on our side.
