### ISSUE TITLE
Supports prompting whether functions imported by imports are being used

### ISSUE THREAD

**Issue by laterdayi** [antfu/unplugin-auto-import#374]
### Clear and concise description of the problem

Supports prompting whether functions imported by imports are being used

### Suggested solution

Supports prompting whether functions imported by imports are being used

```
AutoImport({
imports:['a','b','c','d']
})
```

If a and c are not used, a message is displayed indicating that A and c are not used

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This is considered out-of-scope and we don't have a plan for that. For reference, Nuxt DevTools is able to list unused imports https://nuxt.com/blog/introducing-nuxt-devtools#imports, which means you should be able to implement sometime similar with the existing APIs if you want to.
