### ISSUE TITLE
Vue 3.3 breaks auto import types in `vueTemplate`

### ISSUE THREAD

**Issue by 0x00A1FA** [antfu/unplugin-auto-import#375]
Hello,

I recently upgraded my project to Vue 3.3. I saw on the blog post (https://blog.vuejs.org/posts/vue-3-3) that there have been some changes to the JSX namespace (https://blog.vuejs.org/posts/vue-3-3#jsx-import-source-support).

I'm not getting types for global imports inside `<template>`s. I have `vueTemplate: true,` inside the Vite config, but I'm getting errors when using variables from `auto-imports.d.ts`. They work fine inside `<script setup>`s.

My stack is Vue 3.3.1 + Vite (latest).

Here's an example:

![image](https://github.com/antfu/unplugin-auto-import/assets/110613761/856cad96-2e10-4946-8a46-36dc2fdabbab)

Looking forward to a timely solution.

Thanks!

**Comment by joker77877** [comment]
me too!!

**Comment by antfu** [comment]
I would love to see a minimal reproduction if someone could make one. Not sure if it's some regression related to Volar, as we are extending the `ComponentCustomProperties` interface.

/cc @johnsoncodehk if you have any clue

**Comment by dflock** [comment]
I has run a `taze -I` this morning, which upgraded a bunch of things:

```diff
- @types/node 18.16.9
+ @types/node 18.16.12 (20.1.7 is available)
- @vitest/ui 0.31.0
+ @vitest/ui 0.31.1
- unplugin-auto-import 0.15.3
+ unplugin-auto-import 0.16.0
- unplugin-vue-macros 2.1.6
+ unplugin-vue-macros 2.1.7
- vite 4.3.6
+ vite 4.3.7
- vitest 0.31.0
+ vitest 0.31.1
```
so, I downgraded back to unplugin-auto-import 0.15.3, and I've now got a more valid looking (but completely different) `autoimports.d.ts`:

![image](https://github.com/antfu/unplugin-auto-import/assets/47756/298cc516-0647-4501-82d2-4b78304fc4e6)

**but** - this didn't fix the "Property 'foo' does not exist on type '{ $: ComponentInternalInstance; ..." problem.

**Comment by dflock** [comment]
My broken looking `autoimport.d.ts` file seems to be caused by the combination of:

- unplugin-auto-import 0.16.0
- vue/macros

I had references to vue/macros in various places. I'm not actually using these any more, so I removed them and that fixed the `autoimport.d.ts` brokeness:

```diff
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -14,13 +14,13 @@
     "strictNullChecks": true,
     "allowJs": true,
     "forceConsistentCasingInFileNames": true,
-    "types": ["vitest", "vite/client", "vite-plugin-pages/client", "unplugin-vue-macros/macros-global"],
+    "types": ["vitest", "vite/client", "vite-plugin-pages/client"],
     "paths": {
       "~/*": ["src/*"]
     }
   },
-  "vueCompilerOptions": {
-    "plugins": ["@vue-macros/volar/define-models", "@vue-macros/volar/define-slots"]
-  },
+  // "vueCompilerOptions": {
+  //   "plugins": ["@vue-macros/volar/define-models", "@vue-macros/volar/define-slots"]
+  // },
   "exclude": ["dist", "node_modules"]
 }
diff --git a/vite.config.ts b/vite.config.ts
index 04d8e71..16b1ede 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -67,7 +67,7 @@ export default defineConfig({

     // https://github.com/antfu/unplugin-auto-import
     AutoImport({
-      imports: ['vue', 'vue/macros', 'vue-router', 'vue-i18n', '@vueuse/core', 'vitest'],
+      imports: ['vue', 'vue-router', 'vue-i18n', '@vueuse/core', 'vitest'],
       dts: true,
       dirs: ['./src/composables', './src/stores'],
       vueTemplate: true
```

my `autoimport.d.ts` now appears to be valid and start like this:

```ts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const EffectScope: typeof import('vue')['EffectScope']
```

... this still didn't fix the "Property 'foo' does not exist on type '{ $: ComponentInternalInstance; ..." problem.

**Comment by antfu** [comment]
@dflock your issue is unrelated to the original post, please create another issue instead. Thanks. I am hiding your comments here.

**Comment by k983551019** [comment]
> I would love to see a minimal reproduction if someone could make one. Not sure if it's some regression related to Volar, as we are extending the `ComponentCustomProperties` interface.
> 
> /cc @johnsoncodehk if you have any clue

https://github.com/vuejs/language-tools/issues/3190#issuecomment-1554037716

**Comment by tobychidi** [comment]
This issue would soon become another "me too" movement. with the comments everywhere 🥲

Nuxt says report to Volar. Volar says report to unplugin-auto-imports and you say report to  Volar. 

Here is the original issue on nuxt [nuxt/nuxt#20827](https://github.com/nuxt/nuxt/issues/20827)

**Comment by xiaoxiangmoe** [comment]
Hi all, can you provide us a minimal reproduction to find some clue and then fix it?

**Comment by tobychidi** [comment]
### Reproduction

![image](https://github.com/nuxt/nuxt/assets/111127651/51f17cc2-4624-4240-bcc3-d8d225045052)

This error doesn't seem to be reproducible on Stackblitz so I have included a [github repo](https://github.com/tobychidi/nuxt-utils-import-error)

### Describe the bug

When functions are auto-imported from utils/ composables and used in Vue SFC Template, VsCode throws and error. Yes, I use the latest volar. This error appeared after `pnpm up` That bumped my Vue version to 3.3.1.

I have not tried reverting Vue versions though. 

### Additional context

Example: 
```
Property 'useShowSnack' does not exist on type '{ $: ComponentInternalInstance; $data: {}; $props: { key?: string | number | symbol | undefined; ref?: VNodeRef | undefined; ref_for?: boolean | undefined; ... 8 more ...; style?: unknown; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (arg...'.ts(2339)
```

**Comment by xiaoxiangmoe** [comment]
@tobychidi Hi, I try your repo in both Vue Language Features (Volar) v1.2.0 and v1.7.6. All works well for me.
<img width="1081" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/8111351/32887836-21c0-437f-99f1-21088580d263">

Is there anything I miss? Is there any body can reproduce it will vue-tsc cli?

**Comment by joker77877** [comment]
![image](https://github.com/antfu/unplugin-auto-import/assets/62642184/fdb9c915-0c33-49e6-a6f4-99988101e989)
auto-import.d.ts still reports an error

**Comment by Autumn-one** [comment]
这个问题现在依然存在，使用unplugin-auto-import自动导入的全局函数，在vue的模板文件中直接使用会有类型报错
