### ISSUE TITLE
It doesn't work in my project,where did i go wrong?

### ISSUE THREAD

**Issue by Horzen** [antfu/unplugin-auto-import#380]
when i use vue-cli create a vue 3 project,and config 'unplugin-auto-import' in vue.config.ts like this:
```js
// vue.config.ts
const { defineConfig } = require('@vue/cli-service')

module.exports = defineConfig({
  configureWebpack: {
    plugins: [
      require('unplugin-auto-import/webpack')({
        // dts: 'types/auto-imports.d.ts',
        imports: [
          'vue',
          'vue-router',
          {
            '@vueuse/core': []
          }
        ],
        eslintrc: {
          enabled: true
        }
      })
    ]
  }
})
```

and then,i delete this sentence `import {ref} from 'vue'`

finally,i got a wrong message:'Uncaught ReferenceError: ref is not defined'

platform: macOS
vue version: 3.2.13
pnpm version: 8.3.1
node version: 18.0.0
unplugin-auto-import version: 0.16.1

Help,where did i go wrong?

**Comment by cool1809** [comment]
> 
How to solve it

**Comment by joseehilton147** [comment]
same for me

**Comment by samuel-pp** [comment]
> same for me This is a very serious bug. It works fine for me in development mode, but in production mode, it reports "ref is not defined". Without a testing environment, this would be a disaster.

webpack: 5.91.0
vue: 3.4.27
unplugin-auto-import: 20.1.0
