### ISSUE TITLE
貌似不支持vite默认配置'@vitejs/plugin-react-swc'，我不能在chrome devtools中调试debugger了

### ISSUE THREAD

**Issue by wgsheng06** [antfu/unplugin-auto-import#382]
### Describe the bug

貌似不支持vite默认配置 '@vitejs/plugin-react-swc', 我不能在chrome devtools中调试debugger了
可以拉取我新建的工程，链接为：[https://github.com/wgsheng06/unplugin-un-react-swc-issue-project](https://github.com/wgsheng06/unplugin-un-react-swc-issue-project)

![image](https://github.com/antfu/unplugin-auto-import/assets/34080157/cf8a305f-d508-4875-b173-076b0c7ccf7a)

'@vitejs/plugin-react-swc' 改成 '@vitejs/plugin-react-refresh' 恢复正常

### Suggested solution

暂不知道问题原理在哪里，可能是因为生成sourcemap的问题

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
这个已经合到主分支了
