### ISSUE TITLE
auto-import do not auto inject reactive attribute?

### ISSUE THREAD

**Issue by qiudaoermu** [antfu/unplugin-auto-import#389]
### Describe the bug

// mockLoader.js
```
const mockFiles = import.meta.globEager([
  '../static/mock/img/*.png',
  '../static/icon/*.png',
  '../static/*.png',
]);

for (const i in mockFiles) {
  let key = i.split('/');
  key = key[key.length - 1].replace('.png', '');
  mockFiles[key] = mockFiles[i].default;
  delete mockFiles[i];
}

export default mockFiles;

```
// vite.config.js
```
plugins： 
    AutoImport({
      dts: 'src/auto-imports.d.ts',
      dirs: ['src/mock/**'] // mockLoader.js
)} 

```
app.vue
```
<script lang="ts" setup>
console.log(mockLoader, 'mockLoader'); 
/*
get an image set
admin: "/src/static/admin.png"
*/
<template>
< img :src="mockLoader['admin']"/> // can.not find mockLoader module
</template>
```

<img width="817" alt="image" src="https://github.com/antfu/unplugin-auto-import/assets/13454418/a474e611-33a2-4a84-a67f-6a32a94a298d">

but if set mockLoader as reactive ,it works.
// app.vue
```
<script lang="ts" setup>
console.log(mockLoader, 'mockLoader'); // get an image set
const resolve = reactive({ mockLoader });

<template>
< img :src="resolve.mockLoader['A-image']"/> // can.not find mockLoader module
</template>
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-z761xe?file=package.json,src%2FApp.vue&terminal=dev

### System Info

```Shell
vue: ^3.2.47
vite: ^4.1.4
unplugin-auto-import: ^0.15.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
that admin.png is broken, i changed the img is ok.

**Comment by qiudaoermu** [comment]
the admin.png is just a example file i created,what i want express is:

that is refered from [Vue website](https://vuejs.org/api/sfc-script-setup.html#basic-syntax)

**Imports are exposed in the same fashion. This means you can directly use an imported helper function in template expressions without having to expose it via the methods option:**
```
<script setup>
import { capitalize } from './helpers'
</script>

<template>
  <div>{{ capitalize('hello') }}</div>
</template>
```

so unplugin-auto-import has inject edthe global method, but i think it injected after **setUp** syntactic compied, so the methond is not work.

**Comment by lishaobos** [comment]
that auto import api is before your render fnc. 

 you can make sure your plugin config is right if your method is not work.

![image](https://github.com/antfu/unplugin-auto-import/assets/46661044/20784df2-f2fb-489c-9d5b-e3d6b45c02bf)
![image](https://github.com/antfu/unplugin-auto-import/assets/46661044/bcde4ec2-175a-463f-b221-459bf470c457)
![image](https://github.com/antfu/unplugin-auto-import/assets/46661044/5dd6fc82-0b3e-44f7-8181-627ca826df25)
