### ISSUE TITLE
Import path bug.

### ISSUE THREAD

**Issue by peerless-hero** [antfu/unplugin-auto-import#394]
## error conditions

After investigation, when all the following conditions are met:

- Version number ">=0.16.0" of **unplugin-auto-import**.
- **{** **}** is included in the auto-imported module path.
The generated [auto-imports.d.ts](./types/auto-imports.d.ts) will have an error at line 13.

![image](https://github.com/antfu/unplugin-auto-import/assets/65681376/a708c3fc-b9a8-46b3-97d6-7e58d6eed301)

### Reproduction

https://github.com/peerless-hero/auto-import-error-demo

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 18.70 GB / 31.86 GB
  Binaries:
    Node: 16.19.0 - d:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD     
    npm: 9.6.7 - d:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37)    
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
is reg match error, i see your file name is {id}, Did you have another custom file, like {   id   }?
