### ISSUE TITLE
Can not support vite-ssr auto import

### ISSUE THREAD

**Issue by JerrySir** [antfu/unplugin-auto-import#397]
### Describe the bug

```
AutoImport({
      imports: [
        'vue',
        'vue-router',
        'vue-i18n',
        '@vueuse/head',
        '@vueuse/core',
      ],
      dts: 'src/auto-imports.d.ts',
      dirs: [
        'src/composables',
        'src/store',
        'src/common',
        'src/common/**',
      ],
})
```

use viteSSR:
```
"vite-ssr": "^0.17.1",
```

vercel debug console:
```
ReferenceError: getSEOLinks is not defined
```
but getSEOLinks function in 'src/common/tools.ts'
How to fix this. Thanks

### Reproduction

stable

### System Info

```Shell
pnpm run build:ssr && pnpm run deploy:ssr:prod
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lishaobos** [comment]
need reproduction
