### ISSUE TITLE
Import module with export assignment

### ISSUE THREAD

**Issue by yunsii** [antfu/unplugin-auto-import#399]
### Clear and concise description of the problem

i want to auto import `webextension-polyfill`, but the plugin is not work with export assignment with `@types/webextension-polyfill`
![image](https://github.com/antfu/unplugin-auto-import/assets/18096089/b05eb7f3-7375-46b2-8b9c-e97e5300da56)

### Suggested solution

Maybe configure like this:

```ts
{
  'webextension-polyfill': [[null, 'browser']],
},
```

Generate type:

```ts
declare global {
  const browser: typeof import('webextension-polyfill')
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
need reproduction

**Comment by lishaobos** [comment]
need reproduction

**Comment by yunsii** [comment]
> need reproduction

@lishaobos https://codesandbox.io/p/sandbox/great-fire-v4hpy5 `browser` is not work properly.

**Comment by lishaobos** [comment]
hi，i think should add `export default Browser` in @types/webextension-polyfill/index.d.ts, it is work

![image](https://github.com/antfu/unplugin-auto-import/assets/46661044/9f04f2e9-90d2-4106-bfbb-2ddb78d83327)


![image](https://github.com/antfu/unplugin-auto-import/assets/46661044/6570fa72-b3fe-4c73-aa48-54cc0e8c8ac8)

**Comment by yunsii** [comment]
TypeScript docs: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

 i am not sure if it is proper way?

**Comment by lishaobos** [comment]
This is the simplest solution I can think of

**Comment by yunsii** [comment]
> This is the simplest solution I can think of

Refer ot the source code of webextension-polyfill: https://github.com/mozilla/webextension-polyfill/blob/master/src/browser-polyfill.js

i think patch package from `export =` to `export default` is not a good idea. i test on TypeScript playground and encounter something error like below:

[export assignment playground](https://www.typescriptlang.org/play?module=1#code/DYUwLgBAdgrgtgIxAJwEogOYgB4AcIC8EA9AHoDaADALQCcAugNQAkxA3AFADGwAhgM78IALQCWuAMIB7ACYgAar2CiZvMFOQQA3hwgRR-AIJcuIXGF4JQACn4AuCPzDJRUDAEptuvRGTgYyFCOAHSgbmAAFoQERACsEABkCdDwSGiYOLjBYCBOtu6cegC+HCWZGpBEYpKyCkoqahqcHOXIkABmMFBcYKJSQTl5njo+EKVAA)
![image](https://github.com/antfu/unplugin-auto-import/assets/18096089/3410f470-9641-4bf9-81ce-1acc4c4b0841)

**Comment by lishaobos** [comment]
sorry, it is my fault, you can try like this: 

```
"webextension-polyfill": [['*', 'browser']],
```

**Comment by yunsii** [comment]
@lishaobos i think this syntax should be reflected in the README
```json
{
  'webextension-polyfill': [['*', 'browser']],
}
```

**Comment by lishaobos** [comment]
but if use *, you need browser.default.xx

**Comment by yunsii** [comment]
Oh? but it works for me now 😂

**Comment by lishaobos** [comment]
hh, that is good. mybe i have a wrong usage

**Comment by yunsii** [comment]
> hh, that is good. mybe i have a wrong usage

I will keep watching, that's it for now
