### ISSUE TITLE
在 vuepress2 中无法生效

### ISSUE THREAD

**Issue by WangJincheng4869** [antfu/unplugin-auto-import#409]
### Clear and concise description of the problem

目前不知道是因为 vuepress2 不支持还是这个插件不支持，所以到这里来提问。

### Suggested solution

我想了解一下这个插件的工作原理，我的docs和我的主工程是在一起的。通过此插件配置配置，当我想在 docs 里演示组件时会提示通过自动导入的工具类不存在。看有没有什么方案可以解决这个问题。

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by lishaobos** [comment]
需要一个可复现的 git 仓库

**Comment by WangJincheng4869** [comment]
已经使用 `resolve` 解决
```ts
AutoImport({
          imports: ['vue'],
          dirs: [resolve(__dirname, '../../src/util/**'), resolve(__dirname, '../../src/hooks/**')],
          dts: resolve(__dirname, '../../typings/auto-imports.d.ts'),
          resolvers: [
            ElementPlusResolver({
              // 我们的样式已经进行了全量导入，这里不需要再导入。为什么选择了全量导入？答：因为按需导入会有大量重复的 css 变量，与减小包大小是相悖的，反而全量引入 css 会更好。
              importStyle: false,
            }),
          ],
        }),
```
