### ISSUE TITLE
vite2.9.x + vue2.7.14 build  auto import 失效了

### ISSUE THREAD

**Issue by webaddkevin** [antfu/unplugin-auto-import#413]
### Describe the bug

我的项目vite2.9.x + vue2.7.14，npm run dev 使用插件 可以正常导入，但是options api 中使用provide会从vue中导入provide api这里感觉不需要啊
![image](https://github.com/antfu/unplugin-auto-import/assets/20873249/e8bf909c-b1d6-49fb-b028-1baaacca22b2)，
npm run build 后 vue api 不会自动导入了也不会报错。。 vite升级到3.0就可以了,这个是vite的问题还是插件问题 哪个大神可以帮忙看看

### Reproduction

https://github.com/webaddkevin/vue2-vite-auto-import/tree/main

### System Info

```Shell
node v18.16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
What's the reason to still be on Vite 2.x?

**Comment by webaddkevin** [comment]
> What's the reason to still be on Vite 2.x?

公司老项目去年webpack改的vite， 我怕升级vite带来其他打包兼容性问题。

**Comment by lishaobos** [comment]
可以升级，我之前好几个老项目，都升级了，没啥问题

**Comment by webaddkevin** [comment]
好的， 谢谢大佬🙏。我去升级`vite`去了
