### ISSUE TITLE
标签自动引入时如何默认使用单引号而非双引号

### ISSUE THREAD

**Issue by dongfangyiyu** [antfu/unplugin-auto-import#414]
### Clear and concise description of the problem

默认引入的是双引号

### Suggested solution

是否有配置可以设置

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sorry I don't understand what you are referring to, please provide more information.
