### ISSUE TITLE
v 0.4.8 : nuxt setup failed #<Object> which has only a getter

### ISSUE THREAD

**Issue by TrungRueta** [antfu/unplugin-auto-import#45]
Hi,

I'm using plugin in nuxt project with version v0.4.6 and it working fine. Today i update to 0.4.8 and get error
![image](https://user-images.githubusercontent.com/12226007/135147191-a1a2cbee-296b-4737-9a0c-4e2fcc29b1de.png)

I tried downgrade to 0.4.7 and get same issue. Only working with 0.4.6

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by TrungRueta** [comment]
@antfu Hi Antfu, thank for checking issue. This is codesandbox with nuxt fresh version + typescript.

[https://codesandbox.io/s/unplugin-auto-import-45-b68nc](https://codesandbox.io/s/unplugin-auto-import-45-b68nc)

**Comment by userquin** [comment]
@TrungRueta  you should add the auto import plugin as `dev dependency` not as `dependency`.
