### ISSUE TITLE
Axios import?

### ISSUE THREAD

**Issue by JohnCampionJr** [antfu/unplugin-auto-import#48]
Any way to add axios to this?

I tried this in the imports config , but it didn't work:
```js
 imports: [
        'vue',
        'vue-router',
        '@vueuse/head',
        '@vueuse/core',
        {
          'axios': ['axios']
        }
      ]
```

**Comment by antfu** [comment]
try 

```ts
{
  axios: [
    ['default', 'axios']
  ]
}
```

**Comment by JohnCampionJr** [comment]
Nice!!!!!  Thank you very much.

**Comment by omnjpa27516** [comment]
Please add axios to presets, this is a very commonly used library, it is very necessary to preset
@antfu

**Comment by qinfeng0214** [comment]
@antfu 
Hi,antfu 
I want to ask you, when I export types AxiosRequestConfig  and AxiosResponse from Axios, an error occurs
I used it this way before：import type { AxiosRequestConfig, AxiosResponse } from 'axios'
Now use unplugin-auto-import
`
imports: [
		'vue',
		'vue-router',
		'pinia',
		{
			'@vueuse/core': [
				'useMouse' // import { useMouse } from '@vueuse/core',
				// 设置别名
				// ['useFetch', 'useMyFetch'] // import { useFetch as useMyFetch } from '@vueuse/core',
			],
			axios: ['AxiosRequestConfig', 'AxiosResponse', ['default', 'axios']]
		}
	],
`
auto-import.d.ts:
declare global {
  // type“typeof import("g:/project/vue3-ts-pinia/node_modules/axios/index")” Property does not exist “AxiosRequestConfig”
   const AxiosRequestConfig: typeof import('axios')['AxiosRequestConfig']  
  const AxiosResponse: typeof import('axios')['AxiosResponse']
}
What should I do?

Thank you very much.
