### ISSUE TITLE
RFC: Auto register for types

### ISSUE THREAD

**Issue by antfu** [antfu/unplugin-auto-import#61]
Context:

- https://github.com/antfu/unplugin-auto-import/pull/60#issuecomment-939341877
- https://github.com/antfu/vue-global-api/issues/10

For example, it would be great to have common types like `Ref`, `ComputedRef` globally available when using the Vue preset. I would expect the API to be like

```ts
{
  // auto importing for import
  imports: [
    'vue'
  ],
  // auto importing for types
  types: [
    'vue', // again, we could have presets for it.
    {
      vue: ['Ref', 'ComputedRef']
    }
  ]
}
```

**Comment by userquin** [comment]
@antfu 

Created new branch `feat/auto-register-global-types`: 
- added `types` and split `resolvedImports` on `src/types.ts`: added also some new stuff to support global types
- created `pickTypes` helper function exported on each `unplugin` to allow import partial preset types o full preset: you can see on playground `vite.config.ts` file with partial preset for `vue` using `Ref` and `ComputedRef` on `HelloWorld` sfc
-  added global types for `vue`, `vue-demi`, `@vue/compisition-api`, `pinia` and `vuex`: we need to review them, maybe I forgot some types/interfaces

**Comment by userquin** [comment]
Pushed some changes:
- revert changing `resolvedImports`, included `resolvedTypes` on `TransformOptions`
- use `import` also for types on dts generation
- added `pinia`, `vuex` and `svelte` types

**Comment by jrson83** [comment]
Will you release a npm package with integrated #118 soon?

**Comment by antfu** [comment]
It's not yet possible to have a `.d.ts` redirecting a type from another module.

https://stackblitz.com/edit/node-jjgj6g?file=index.ts

I'd consider it as a limitation of TypeScript. If anyone finds a solution, please comment with a fork of the Stackblitz playground and then we could discuss how to implement that. Thanks.

**Comment by ennioVisco** [comment]
> 

According to this: https://gist.github.com/Bnaya/97080f563fa8242e26a041732185a260 it depends to some typescript flag that can (and perhaps should) be disabled?

**Comment by terran42** [comment]
@antfu Maybe I misunderstood, but is this not what you want?

- https://stackblitz.com/edit/node-v1ncfz?file=imports.d.ts%3AL11
- https://stackblitz.com/edit/node-v1ncfz?file=global.d.ts%3AL2-L2  (commented out, but works too when L11 in `imports.d.ts` is commented out)

Both seems to work, at least to my needs:
- `Ref<number>` in `index.ts` has hint `type Ref<T> = Ref<any>`
-  Cmd+Click directs me to the right place in `imports.d.ts` or `global.d.ts`
-  Cmd+Click in `imports.d.ts` or `global.d.ts` on `V.Ref` or `import('vue').Ref` leads to definitions in Vue.

I'm happy with that.

**Comment by KeyToLove** [comment]
> It's not yet possible to have a `.d.ts` redirecting a type from another module.
> 
> https://stackblitz.com/edit/node-jjgj6g?file=index.ts
> 
> I'd consider it as a limitation of TypeScript. If anyone finds a solution, please comment with a fork of the Stackblitz playground and then we could discuss how to implement that. Thanks.

也就是说现阶段想使用依赖的interface或其它类型定义（e.g: Ref），依旧需要通过显示引入的方式么🤔️

**Comment by MKraust** [comment]
@antfu TypeScript 5.0 introduces `export type * from '...'`. Stable release is scheduled to March 14th. 
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#support-for-export-type

Any chances that type auto-imports could be implemented in the near future after TS 5.0 release?

**Comment by byronogis** [comment]
> dirs 配置的目标文件 中的类型 怎么自动导出

现在(截至v0.18.2), 在本地有两种办法

1. 本地打补丁, 启用类型包含

比如使用 pnpm: `pnpm patch unplugin-auto-imports`  

在 dist/chunk* 文件中查找 scanExports 方法, 将第二个参数改为 true, 
对应的源码见
- https://github.com/unplugin/unplugin-auto-import/blob/e88f9232a0f7e91dab548296cd3bf1efa61b2bcd/src/core/ctx.ts#L34 
- https://github.com/unjs/unimport/blob/a851b73c6dcf4aaf7309f275363dc510bd8e7ebb/src/node/scan-dirs.ts#L74

2. 手动配置 imports 选项, 枚举需要自动导入的类型, 比如

```ts
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import AutoImport from 'unplugin-auto-import/vite'

export default defineConfig(() => {
  return {
    plugins: [
      AutoImport({
        imports: [
          {
            from: resolve(__dirname, 'src/types/memory'),
            imports: [
              'MemoryItem',
            ],
            type: true,
          },
        ]
      })
    ]
  }
})

```

第一种方式启用文件夹的类型包含后, 暂不清楚是否有其它副作用, 好处是不用自己枚举了, 只要在放进 dirs 选项就可以;
第二种方式不需要侵入包, 但需要自己一个一个列出来.

**Comment by lisonge** [comment]
> 手动配置 imports 选项, 枚举需要自动导入的类型, 比如

automatically get the type identifier name list to build preset

```ts
import ts from 'typescript';
import fs from 'node:fs/promises';
import path from 'node:path';

const getTsExportNamePreset = async (fileName: string) => {
  const code = await fs.readFile(fileName, 'utf-8');
  const source = ts.createSourceFile(
    path.basename(fileName),
    code,
    ts.ScriptTarget.Latest
  );
  const nodes = source.statements.filter((node) => {
    return (
      (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) &&
      node.modifiers?.[0]?.kind === ts.SyntaxKind.ExportKeyword
    );
  }) as (ts.InterfaceDeclaration | ts.TypeAliasDeclaration)[];
  const imports = nodes.map((n) => n.name.escapedText.toString());

  return {
    from: fileName,
    imports,
    type: true,
  };
};

/*
autoImport({
  imports: [await getTsExportNamePreset('./src/auto-import/types.ts')],
});
*/

```
