### ISSUE TITLE
Bundle size increases with the plugin when used in a quasar project

### ISSUE THREAD

**Issue by soulsam480** [antfu/unplugin-auto-import#68]
Hii @antfu, When a normal build is done on a quasar project, the build bundle size is `500kb` smaller than a build with the plugin used.

Steps to reproduce
- create a new quasar cli project
- do a normal build
- check `dist/spa` folder size
- install `unplugin-auto-import`
- add it in quasar config with the following presets installed
``` js
 chainWebpack(chain) {
        chain.plugin('unplugin-auto-import').use(
          AutoImportPlugin({
            // targets to transform
            include: [
              /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
              /\.vue$/,
              /\.vue\?vue/, // .vue
              /\.md$/, // .md
            ],

            // global imports to register
            imports: [
              // presets
              'vue',
              'vue-router',
              'vuex',
              'quasar',
            ],
          })
        );
      },
```
- remove all vue API imports and run a build
- check `dist/spa` folder size
- it's higher than that of the normal build

What's expected
- The bundle size should remain the same because we have `Tree shaking` in place

What happenes
- The bundle size with the plugin is larger than without the plugin

Please let me know if you need a repo to reproduce. I did it with a project with around 20 `.vue` files and `10` plus `.ts` files

**Comment by soulsam480** [comment]
@antfu Hey, can you help on this, please

**Comment by antfu** [comment]
All this plugin does is inject the import statement for the modules and nothing else. I believe this is more like a bundler or deps resolving issue. I am open for PR that fix the preset if there is anything missing, otherwise this is considered as out-of-scope.
