### ISSUE TITLE
Is it feasible to automatically generate a list with auto imported api names for ESLint config file?

### ISSUE THREAD

**Issue by ItsRyanWu** [antfu/unplugin-auto-import#69]
So that ESLint won't emit 'undefined' type error for these api
For e.g.

![image](https://user-images.githubusercontent.com/17338101/139012801-52f6051a-0c26-4944-92ed-109f5d1ef458.png)

**Comment by lukeeno** [comment]
@sschneider-ihre-pvs in which file (config) should I put this line exactly?

I also have another auto-generated file `components.d.ts`. The line you provided seems to support only one file. How do I overcome this issue?

Thanks

**Comment by antfu** [comment]
If someone really needs this. I am happy to receive a PR to generate `components.json` (just like how dts works) to be consumed by the eslint config. Would that make sense to you?

**Comment by 0x009922** [comment]
I guess the solution may be to make a simple ESLint plugin which would receive path to the generated `.d.ts` file, parse it and extend globals. But idk how to pass options to ESLint plugins.

Btw, my `.eslintrc.js` that solves the problem:

```js
/* eslint-disable @typescript-eslint/no-require-imports */
const path = require('path')
const fs = require('fs')

function parseAutoImportsDts(contents) {
  const matchResults = contents.matchAll(/^\s+const (\w+): typeof import/gm)
  return Array.from(matchResults, ([, word]) => word)
}

function uiPackageAutoImportGlobals() {
  const SRC = path.resolve(__dirname, './packages/ui/auto-imports.d.ts')

  const contents = fs.readFileSync(SRC, { encoding: 'utf-8' })
  const parsed = parseAutoImportsDts(contents)
  return parsed.reduce((acc, word) => {
    acc[word] = 'readonly'
    return acc
  }, {})
}

module.exports = {
  // ...
  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly',
    defineExpose: 'readonly',
    withDefaults: 'readonly',
    ...uiPackageAutoImportGlobals(),
  }
}

```

**Comment by Dirian9754** [comment]
> @sschneider-ihre-pvs in which file (config) should I put this line exactly?
> 
> I also have another auto-generated file `components.d.ts`. The line you provided seems to support only one file. How do I overcome this issue?
> 
> Thanks

have you solved it? you can put it in the rules of eslint configure file.

**Comment by Dirian9754** [comment]
> dts: '<path to resolved dts files>/auto-imports

ok， I  am was wrong，That's invalid， I don't know solve it

**Comment by Dirian9754** [comment]
> If someone really needs this. I am happy to receive a PR to generate `components.json` (just like how dts works) to be consumed by the eslint config. Would that make sense to you?

how to solve this eslint  problem?

**Comment by sschneider-ihre-pvs** [comment]
> @sschneider-ihre-pvs in which file (config) should I put this line exactly?
> 
> I also have another auto-generated file `components.d.ts`. The line you provided seems to support only one file. How do I overcome this issue?
> 
> Thanks

In the options of the autoimport config
