### ISSUE TITLE
Any chance to replace `vite-plugin-components` too?

### ISSUE THREAD

**Issue by fyeeme** [antfu/unplugin-auto-import#7]
`vite-plugin-icons` and compents auto import are now depends on **vite-plugin-components**, and generate types in **components.d.ts**.

While  `unplugin-auto-import` in **auto-imports.d.ts**.

is there any chance to combine  `vite-plugin-components` in  `unplugin-auto-import`?

**Comment by antfu** [comment]
They are trying to solve different problem in different scopes. I don't see they share a general common solution. So probably no.
