### ISSUE TITLE
项目名中含有特殊符号

### ISSUE THREAD

**Issue by hezulong1** [antfu/unplugin-auto-import#72]
项目名中存在特殊符号，发现无法自动导入，运行起来出现 `ReferenceError: *** is not defined`。虽然修改文件夹名称就可以，但还请兼容下，谢谢🙏。

![image](https://user-images.githubusercontent.com/28552513/139579939-64614360-9575-43a0-8728-8afdd00bd430.png)

![image](https://user-images.githubusercontent.com/28552513/139579977-cdaf8331-e8be-4256-b5b3-3b06d53fbdde.png)

**Comment by antfu** [comment]
What's the symbol causing that?

**Comment by hezulong1** [comment]
> What's the symbol causing that?

半角中的 `.` 符号
