### ISSUE TITLE
[vue-router] issue with `vite-plugin-pages`

### ISSUE THREAD

**Issue by web2033** [antfu/unplugin-auto-import#8]
I tried on a project with https://github.com/hannoeru/vite-plugin-pages and it breaks

After removing `import { useRoute } from 'vue-router'`

Uncaught ReferenceError: useRoute is not defined

**Comment by antfu** [comment]
IDK what's going on with your project, but I believe https://github.com/antfu/vitesse is working like that. Please provide a minimal repro.
