### ISSUE TITLE
ref is not defined for production build

### ISSUE THREAD

**Issue by mlhou** [antfu/unplugin-auto-import#89]
works fine in  development mode, but in production build with npm run build, it shows  ‘ref is not defined’

```
<template>
  <div ref="divRef">test</div>
</template>

<script setup>
const divRef = ref(null);
</script>

<style scoped></style>
```

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by mlhou** [comment]
[my-project.zip](https://github.com/antfu/unplugin-auto-import/files/7621754/my-project.zip)
please refer to attached files. Thanks.
It seems that the plugin auto imports unref for the [Template Refs](https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs), 
if I just use simple ref object, it can work both in development mode and production build
```
<template>
   <div>
    {{message}}
  </div>
</template>
<script setup>
const message = ref('hello')
</script>
```
however, if I ref to template element or component instance, it can work in development mode but it doesn't work for production build
```
<template>
  <div ref="divRef">test</div>
</template>

<script setup>
const divRef = ref(null);
</script>
```

**Comment by Rigo-m** [comment]
We have the same problem. Using a template Ref gives an error in production. Did you have any time to take a look at it @antfu ?

**Comment by Rye-z** [comment]
Same problem, try [vue-global-api](https://github.com/antfu/vue-global-api) , registor `ref` as global api and it works in production. 
```
// main.js
import 'vue-global-api/ref'
```

**Comment by Archetipo95** [comment]
> Same problem, try [vue-global-api](https://github.com/antfu/vue-global-api) , registor `ref` as global api and it works in production.
> 
> ```
> // main.js
> import 'vue-global-api/ref'
> ```

For now this solved the problem. Thanks!

**Comment by brother-water** [comment]
Same problem

**Comment by sufuWang** [comment]
`vue-global-api` can resolve `ref` is not find ，but can't resolve `Ref` is not find

**Comment by kaiser-9527** [comment]
> [my-project.zip](https://github.com/antfu/unplugin-auto-import/files/7621754/my-project.zip) please refer to attached files. Thanks. It seems that the plugin auto imports unref for the [Template Refs](https://v3.vuejs.org/guide/composition-api-template-refs.html#template-refs), if I just use simple ref object, it can work both in development mode and production build
> 
> ```
> <template>
>    <div>
>     {{message}}
>   </div>
> </template>
> <script setup>
> const message = ref('hello')
> </script>
> ```
> 
> however, if I ref to template element or component instance, it can work in development mode but it doesn't work for production build
> 
> ```
> <template>
>   <div ref="divRef">test</div>
> </template>
> 
> <script setup>
> const divRef = ref(null);
> </script>
> ```

```
<template>
  <main>{{ count }}</main>
</template>
<script setup lang="ts">
const count = ref([1, 3])
</script>
```

It's a simple ref usage, but also got the same error `error TS2304: Cannot find name 'ref'.`,
the version is `"unplugin-auto-import": "^0.5.5"`.  like this plugin vary much, but got this error, is depressed

**Comment by rubiin** [comment]
got simiar issue in build

**Comment by antfu** [comment]
Please upgrade to the latest version and try again. If it still fails to you, please send a PR to add a failed tests under https://github.com/antfu/unplugin-auto-import/tree/main/test/fixtures. Thanks
