### ISSUE TITLE
Eslint shows that 'ref' is not defined in VSCode.

### ISSUE THREAD

**Issue by Huang-Jinxian** [antfu/unplugin-auto-import#92]
![image](https://user-images.githubusercontent.com/22197930/145054332-9d80e2b9-b4e6-4a8a-8478-c2573cd3bb0a.png)
Eslint shows me that `ref` is not defined.
the following is my project conf.
`veu.config.js`
![image](https://user-images.githubusercontent.com/22197930/145055040-70ce90db-3e90-4d51-a067-1dbcfefcff47.png)
`tsconfig.js`
![image](https://user-images.githubusercontent.com/22197930/145054931-f616d4bc-0809-453a-8afc-fc2ea1255607.png)

this looks the same as #3 .

**Comment by sdynggg** [comment]
tsconfig.json add
 "exclude": [
    "auto-import.d.ts"
  ]

**Comment by antfu** [comment]
`"no-unref": "off"`

**Comment by liujiaqi222** [comment]
> `"no-unref": "off"`  应该是'no-undef': 'off',我直接复制了过去，然后发现，怎么也禁用不掉，一个小typo
